### ISSUE TITLE
Documentation on Adding content

### ISSUE THREAD

**Issue by Xqua** [Orcpub/orcpub#104]
Hi, 

What is the best way to dump a lot of race and objects into the DB so that I don't have to lad them through the "Local Vault" style loading ? 
AKA how do I use my packs on my own instances, so that they are permanently in the DB, and is this possible ? 
I have the orcbrew files, I'm looking at how to import them into the datomic DB !

Any help greatly appreciated !

**Comment by datdamnzotz** [comment]
There is no storage in the db for races, spells etc... the application isn't coded that way.
The database is only there to store the relationships to the character to what is in the orcbrew files.

I suppose you could recode for that... but that isn't the charter of this repo.

**Comment by RobinLefebvre** [comment]
Your .orcbrew files won't be applicable on the DB, they are being stored into Window.localStorage["plugins"] on your browser.

Making sure some default content is available on your fork of the site is doable either by editing the clojure files that hold the data, or maybe by injecting some file into localStorage via front-end JS.

All I can say is that for now, there's no real effective way to do so. It is the second time I see this come up, so maybe feature request for later ?

**Comment by Xqua** [comment]
@johnliss Thanks !

@RobinLefebvre Thanks 
Yes I just went through the code to see how the default data was added... 
Indeed, it seems easier to write an injector than make new default files IMO ! 

I don't really know Clojure at all though ..... But the way I think of it would be:

- Hijack the import / merge function from the import tool
- Read from a local folder instead of the Web JS
- Inject unto the localStore

(and doing it nice with a volume mount docker style)

Basically hijacking this:
```
(reg-event-fx
 ::e5/import-plugin
 (fn [{:keys [db]} [_ plugin-name plugin-text]]
   (let [plugin (try
                  (reader/read-string plugin-text)
                  (catch js/Error e nil))]
     (cond 
       (spec/valid? ::e5/plugin plugin)
       {:dispatch-n [[::e5/set-plugins (assoc (:plugins db)
                                              plugin-name
                                              plugin)]
                     [:show-warning-message (str "File imported as '" plugin-name "'. To be safe, you should 'Export All' and save to a safe location now.")]]}

       (spec/valid? ::e5/plugins plugin)
       {:dispatch-n [[::e5/set-plugins (e5/merge-all-plugins
                                        (:plugins db)
                                        plugin)]
                     [:show-warning-message "Imported content was merged into your existing content. To be safe, you should 'Export All' and save to a safe location now."]]}
       
       :else
       (do
         (prn "PLUGIN" plugin)
         (prn "INVALID PLUGINS FILE"
              (spec/explain-data ::e5/plugins plugin))
         (prn "INVALID PLUGIN FILE"
              (spec/explain-data ::e5/plugin plugin))
         {:dispatch [:show-error-message "Invalid .orcbrew file"]})))))
```

But as I said ..... I have no clue how to do this lol ! 
I can dev on Python / Rails / Node  ... but I don't really have the time to learn Clojure ATM

**Comment by RobinLefebvre** [comment]
Understandable. Indeed, the piece of code you pointed to could be the perfect spot to add in your own content. I can't yet find a way to neatly do so, hopefully I will.

I do still believe this use-case is quite specific. When hosting your own site, you can add a link to a cloud space containing the file you want "everyone" to have access to. That and a link to a video or text about how to import content, and it is unlikely it would be a big hassle.

**Comment by datdamnzotz** [comment]
Your close @Xqua the actual writes of the plugin system does it [here](https://github.com/Orcpub/orcpub/blob/develop/src/cljs/orcpub/dnd/e5/db.cljs#L147)

If you redirect that to a db, then you could store everything.
`(defn user->local-store `

Of course you have to make schema changes to the db as well.

**Comment by Xqua** [comment]
@RobinLefebvre That is true ! The reason I want to do this is that I found that the localstore "often" looses the content stored in it, and I kinda got tired of freaking out why all the characters were suddenly all wrong xD, so I thought, hey, what if I host it and inject it ! That way it'll be server side and stable ! 

I'm thinking now .... could I hack Nginx to inject to the local store .... XD but that's more of a hack lol

But I guess the clean way to do it would be to do like @johnliss is proposing, create schema on the DB, and have a read/write function...

@johnliss thanks ! Hum so that's where all the elements are written on the LocalStore DB, but if I understand this correctly, this part is on the JS side ? so it'll be client facing not server facing, so it couldn't reach the DB or files on the server no? I don't know how Closure handles server/client sides

How are the default item / race handled ? Are they hard coded into the JS code ? or are they pulled from somewhere ?
