### ISSUE TITLE
Add Folders to Character List

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#119]
**Is your feature request related to a problem? Please describe.**
Currently the only sorting for the Character List is done alphabetically.

**Describe the solution you'd like**
The option to sort Characters into Folders (named whatever you want).

**Comment by Butterfly-Dragon** [comment]
why not use the party page? that seems exactly what it's for.

**Comment by DivertedCircle** [comment]
I do use the party page, the point is that my character list is huge and I want to trim it down into folders.

**Comment by Butterfly-Dragon** [comment]
That's what i meant. Parties are just tags.

You can have the same character on multiple parties and use parties as folders.

What i'm hearing and you're not saying is that you want collapsible parties so they don't have to stay open 🤣

**Comment by DivertedCircle** [comment]
Perhaps I should have clarified but Folders in my mind are exactly like Folders on a computer system, they're collapsed unless you're that particular folder.

**Comment by datdamnzotz** [comment]
Isn't this a duplicate of #52 ?

**Comment by DivertedCircle** [comment]
Whoops, forgot I requested it already.
