### ISSUE TITLE
Password Reset and Auth Emails have wrong URL string

### ISSUE THREAD

**Issue by datdamnzotz** [Orcpub/orcpub#12]
The email "password reset" has the wrong protocol/host/port 

Example:
https://192.168.0.11/pages/send-password-reset-page

Generated:

Dear OrcPub Patron

We received a request to reset your password, to do so please go to the following URL to complete the reset.

http://orcpub:8890/pages/reset-password-page?key=632e6951-95b4-4250-8532-485b32b800ba

If you did NOT request a reset, please do no click on the link.

Sincerely,

The OrcPub Team

Expected url should be: 

https://192.168.0.11/pages/reset-password-page?key=632e6951-95b4-4250-8532-485b32b800ba

**Comment by datdamnzotz** [comment]
they are built off of base-url which is defined in https://github.com/Orcpub/orcpub/blob/develop/src/clj/orcpub/oauth.clj#L21

Just need some logic to pull the host header from the reverse proxy... and set the base url accordingly...

**Comment by MeanderingCode** [comment]
Addressed by #24

**Comment by Demonsthere** [comment]
With #24 merged is still issue still valid?

**Comment by MeanderingCode** [comment]
If we can validate that it is working, we can close this issue.

**Comment by doug-w** [comment]
With #24 merged in the scheme is incorrect.  https://nginx-reverse-proxy/ leads to a registration e-mail of http://nginx-reverse-proxy

**Comment by datdamnzotz** [comment]
Fixed with #24
