### ISSUE TITLE
Hit Dice representation problems in character sheet

### ISSUE THREAD

**Issue by Butterfly-Dragon** [Orcpub/orcpub#120]
**Describe the bug**
An hit die is not a pure die. and the grouping is wrong

**To Reproduce**
Create any character with at least 1 level

**Expected behavior**
show something along the lines of:
3x (1d8+1) / 3x (1d12+1)

![image](https://user-images.githubusercontent.com/33538906/54685369-f0090f00-4b16-11e9-9d32-037f64724ec1.png)

Writing each die of each size with their modifier as a different entity and keeping the contitution modifier as a "single die" thing. So players know they have some dice of one kind and some of another kind.

As far as i remember there is no way for a character to have hit die with different constitution/bonus values depending on the class, but even if the class/subclass redefined the hit die for that class by adding a "+1 per level hit points" that usually has no effect on the hit die, just on the total hit points, so i'm ignoring such fringe cases.

**Screenshots Of The Current Situation**

the used layout is a pure XdY for single class or WdX / YdZ for multiclass depending on how many classes the character has, which could get lengthy i've made 2 random quick characters of 2 classes with 3 levels each to show the problem.

example 1:

2 classes with different hit die size. as you can see nowhere is the constitution stated, and with a layout such as 3d8/3d12 writing the +1 constitution as "3d8+1/3d12+1" or "3d8/3d12 +1" would probably just confuse players

![image](https://user-images.githubusercontent.com/33538906/54693096-577a8b00-4b26-11e9-8ffb-47a76dcf8689.png)
This should read: 3x (1d8+1) / 3x (1d12+1)

example 2:

2 classes with the same hit die size. These things should be grouped as we're talking about hit dice here, not class levelling. this should not read 3d8/3d8 

![image](https://user-images.githubusercontent.com/33538906/54693872-9ceb8800-4b27-11e9-90c5-7114d6222850.png)
This should read: 6x (1d8+1)

**Comment by datdamnzotz** [comment]
Good find! 

I took a look at this, and IMHO the whole to PDF needs to be re-architected.  Egad this is a mess.
This really really effects all mutil class characters all over the sheet.

I was able to reformat the Hit dice strings to a lvlx(1dhd+con) format, but for multi class characters it gets truncated in the total box.  The total box only allows for 9 characters and the Hit Dice box only allows 26 characters.  This appears to be the reason for the lvl d hd format.  

![image](https://user-images.githubusercontent.com/3913859/55689713-2fbc5d00-5945-11e9-8d83-cfa9994be223.png)

Short term I can move it to the lower box and reformat like this:
![image](https://user-images.githubusercontent.com/3913859/55689769-cdb02780-5945-11e9-8f99-a5e84f2ec813.png)

But again, I think the whole PDF print needs to be re-architected so it flows better.

**Comment by Butterfly-Dragon** [comment]
Well there are a total of 4 hit die types (d6 d8 d10 d12).

So... if you group hit dice by type and not by class, at most you'd have a string of ... let's see...

10x(d6+5) 8x(d8+5) 1x(d10+5) 1x(d12+5)
the above is 38 characters. And... damn it gets really tiny

But then again most people will take 2 classes or 3 at most and usually you end up with 2 different kinds of dice at most and one of them stays in the single digits.. sooo... i'd say it's 20 characters at most with a level 8 fighter level 12 barbarian.

**Comment by datdamnzotz** [comment]
with two it comes out like 
![image](https://user-images.githubusercontent.com/3913859/55690110-431df700-594a-11e9-92a9-c55b9a4766ec.png)

I even messed with the form a bit to take out total.

**Comment by datdamnzotz** [comment]
which do you prefer
![image](https://user-images.githubusercontent.com/3913859/55690378-1c61bf80-594e-11e9-87a2-d6f37cfb0ecf.png)
![image](https://user-images.githubusercontent.com/3913859/55690437-ec66ec00-594e-11e9-8473-792c2afa525e.png)

**Comment by Butterfly-Dragon** [comment]
hit dice don't care the class they come from so just listing how many of each **_of the 4 kinds_** rather than dividing them by class should work better and also allow people to take notes. Also to maximize "taking notes" aligning left would be better.

**Comment by datdamnzotz** [comment]
I get what you are saying, but some of the feed back, some users wanted to see which hit dice came from which class.

**Comment by Butterfly-Dragon** [comment]
.... makes no sense... neither mechanically not in any other way... the space is very limited and there are no classes that change the hit die for themselves alone 🤔

... but then again i've seen plenty of weird requests, and mine probably fell into that. It's just that what you're already showing looks sooooo tiny... i dunno.
