### ISSUE TITLE
discord images not getting attached

### ISSUE THREAD

**Issue by Butterfly-Dragon** [Orcpub/orcpub#124]
**Describe the bug**
When printing a character sheet where images from a Discord source have been provided, said images often do not appear. Most notably several links work in the preview of the character builder, but not on the PDF character sheets.

**To Reproduce**
right click on an image from discord and "copy link" (do so from the thumbnail, which is the original image, as the zoomed image is actually a script)

paste it in the url field for the character/faction image

it usually should appear

Create the character PDF.

The image fields on the charsheet are empty and must be filled manually.

**Expected behavior**
to see the images just like one see the previews on the character builder.

**Comment by datdamnzotz** [comment]
Actual error.  I'll keep digging... might be they are just blocking.

`user=> java.io.IOException: Server returned HTTP response code: 403 for URL: https://cdn.discordapp.com/attachments/554870272239337474/564422327660707855/unknown.png
 at sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1894)
    sun.net.www.protocol.http.HttpURLConnection.getInputStream (HttpURLConnection.java:1492)
    sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream (HttpsURLConnectionImpl.java:263)
    java.net.URL.openStream (URL.java:1045)
    orcpub.pdf$draw_non_jpg.invokeStatic (pdf.clj:96)
    orcpub.pdf$draw_non_jpg.invoke (pdf.clj:94)
    orcpub.pdf$draw_image_BANG_.invokeStatic (pdf.clj:112)
    orcpub.pdf$draw_image_BANG_.invoke (pdf.clj:106)
    orcpub.routes$character_pdf_2$fn__43285.invoke (routes.clj:518)
    orcpub.routes$character_pdf_2.invokeStatic (routes.clj:511)
    orcpub.routes$character_pdf_2.invoke (routes.clj:497)
    io.pedestal.interceptor$eval21656$fn__21657$fn__21658.invoke (interceptor.clj:41)
    io.pedestal.interceptor.chain$try_f.invokeStatic (chain.clj:52)
    io.pedestal.interceptor.chain$try_f.invoke (chain.clj:42)
    io.pedestal.interceptor.chain$process_all_with_binding.invokeStatic (chain.clj:152)
    io.pedestal.interceptor.chain$process_all_with_binding.invoke (chain.clj:129)
    io.pedestal.interceptor.chain$process_all$fn__22196.invoke (chain.clj:165)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$with_bindings_STAR_.invokeStatic (core.clj:1973)
    clojure.core$with_bindings_STAR_.doInvoke (core.clj:1973)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    io.pedestal.interceptor.chain$process_all.invokeStatic (chain.clj:163)
    io.pedestal.interceptor.chain$process_all.invoke (chain.clj:159)
    io.pedestal.interceptor.chain$enter_all.invokeStatic (chain.clj:212)
    io.pedestal.interceptor.chain$enter_all.invoke (chain.clj:206)
    io.pedestal.interceptor.chain$execute.invokeStatic (chain.clj:356)
    io.pedestal.interceptor.chain$execute.invoke (chain.clj:329)
    io.pedestal.interceptor.chain$execute.invokeStatic (chain.clj:366)
    io.pedestal.interceptor.chain$execute.invoke (chain.clj:329)
    io.pedestal.http.impl.servlet_interceptor$interceptor_service_fn$fn__26085.invoke (servlet_interceptor.clj:350)
    io.pedestal.http.servlet.FnServlet.service (servlet.clj:28)
    org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:845)
    org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:583)
    org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
    org.eclipse.jetty.server.handler.gzip.GzipHandler.handle (GzipHandler.java:399)
    org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1162)
    org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:511)
    org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1092)
    org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
    org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:134)
    org.eclipse.jetty.server.Server.handle (Server.java:518)
    org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:308)
    org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:244)
    org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:273)
    org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
    org.eclipse.jetty.io.SelectChannelEndPoint$2.run (SelectChannelEndPoint.java:93)
    org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun (ExecuteProduceConsume.java:246)
    org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run (ExecuteProduceConsume.java:156)
    org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:654)
    org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:572)
    java.lang.Thread.run (Thread.java:748)
"failed loading image" nil`

**Comment by datdamnzotz** [comment]
Possible fix? https://stackoverflow.com/questions/41069457/403-error-when-trying-to-access-an-image-url

**Comment by codeGlaze** [comment]
I think discord server urls are private, no?

**Comment by datdamnzotz** [comment]
They don't appear to be, I think it is because is it missing a user-agent

```
C:\Tmp>wget https://cdn.discordapp.com/attachments/554870272239337474/564422327660707855/unknown.png
--2019-04-07 19:59:55--  https://cdn.discordapp.com/attachments/554870272239337474/564422327660707855/unknown.png
Resolving cdn.discordapp.com (cdn.discordapp.com)... 104.16.10.231, 104.16.12.231, 104.16.9.231, ...
Connecting to cdn.discordapp.com (cdn.discordapp.com)|104.16.10.231|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 80614 (79K) [image/png]
Saving to: 'unknown.png'

unknown.png                   100%[=================================================>]  78.72K  --.-KB/s    in 0.03s

2019-04-07 19:59:56 (2.94 MB/s) - 'unknown.png' saved [80614/80614]```

**Comment by datdamnzotz** [comment]
It's the user agent that discord blocks.
