### ISSUE TITLE
Wrong requirements for Ritual Caster

### ISSUE THREAD

**Issue by Demonsthere** [Orcpub/orcpub#134]
**Describe the bug**
Currently Ritual Caster feat requires 13 WIS, however it should be WIS or INT according to [5etools](https://5etools.com/feats.html#ritual%20caster_phb)

**To Reproduce**
Create a character with more than 13 INT but less than 13 WIS, try to get the feat

**Expected behavior**
INT is respected for the feat

**Comment by Demonsthere** [comment]
After some investigation it seems that our codebase does not support the OR in the requirements, and instead requires both, wisdom and int to be above 13

**Comment by DivertedCircle** [comment]
Make sure you have the most up to date PHB file, Ritual Caster was split into two feats awhile ago; one for INT based and one for WIS based.
![image](https://user-images.githubusercontent.com/26470570/55505726-fc11c800-5610-11e9-9d98-22a041c9f4e8.png)

**Comment by Demonsthere** [comment]
Yes, i have found that, i need to update :). Closing
