### ISSUE TITLE
Sources enabled/disabled per character

### ISSUE THREAD

**Issue by The1Krutz** [Orcpub/orcpub#155]
**Is your feature request related to a problem? Please describe.**
I have multiple characters in multiple games with different allowed sources. This creates a problem when the only option to enable/disable content is from the global "my content" page.
Turning a source on shows it for characters where I don't want it to show. Turning a source off breaks existing characters which depend on it.

**Describe the solution you'd like**
_In a perfect world_: Per-character settings for whether a given source is included in the options. Old Orcpub (prior to the SRD purge) used to have this feature, where any source could be enabled or disabled for a character without affecting other characters.

_Would also solve the problem and is probably a lot less work_: Include the name of the source in the "show info" block. Just whatever the name is on the "my content" page where the option comes from, at the bottom of the "show info" block for that option. That's enough to tell me where the thing comes from so I can just leave everything globally on, but still make informed choices.

**Describe alternatives you've considered**
Just dealing with it, honestly? Using multiple browsers with different content settings is a hassle, but it also technically works.

**Comment by datdamnzotz** [comment]
ooo this is a awesome request..  Hard to do, but a awesome Idea.
A short work around would be load content as a character.orcbrew, and just toggle on and off between the two... but it would be cooler if it was available under the character as source you can flip on and off.  

I like it.

Architecturally it might be possible, we will have to dig and see how it is applied.  I think most of the logic is hard-coded.

**Comment by willfaulds** [comment]
I was thinking about this and whether a careful implementation could allow for manual correction of the issue by offering non-allowable spells (ie homebrew spells to be only accessible to a certain class/background etc)
