### ISSUE TITLE
A separate ability selection table (like the one with spells) for monks

### ISSUE THREAD

**Issue by sirteabag** [Orcpub/orcpub#178]
1.   1. I was creating a way of the four elements monk in orcpub and I wasn't a fan of the huge
      text block I saw in the features window.
      2. In the spell maker I didn't like that I couldn't make a monk "spell" (ability)

2.   1. A separate window, like the one for spells for monks (way of the 4 elements) in which you can 
      select which spells you chose throughout leveling up.
      2. You'd add a monk as a spell type.

**Comment by KingMob** [comment]
Closed as duplicate of #179
