### ISSUE TITLE
Allow opening in a new tab/window

### ISSUE THREAD

**Issue by kamander** [Orcpub/orcpub#180]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to open menu options or characters in a new tab or window..

**Describe the solution you'd like**
Allow characters to be opened in a new tab/window. 
Allow all menu options (spells, monsters, items, etc.) to be opened in new tab/window.

**Describe alternatives you've considered**
If, for some reason, it is not possible or advisable to open characters in new tabs/windows, because having multiple characters open at a time could cause problems, at least allow it from the home page (https://www.dungeonmastersvault.com/)

**Comment by codeGlaze** [comment]
That's more a side effect of the site being built with React as an SPA (Single Page App). It's an annoyance of mine as well. You can copy the link to your character and just paste it in a new tab.

I'm not entirely sure what change would need to be made to allow a Ctrl+click situation to work. 🤔

**Comment by jeliss** [comment]
Right click the 
![image](https://user-images.githubusercontent.com/8504664/58050075-99ff1a80-7b0b-11e9-9a29-cb04b83d17ad.png) and open in new tab.  Works for me.

I wouldn't recommend editing any of the same characters in two different tabs, but to display, you are only limited by the resources of your machine.

**Comment by datdamnzotz** [comment]
You can right click open in new tab
![image](https://user-images.githubusercontent.com/3913859/58050509-c8312a00-7b0c-11e9-8d29-8615fa70896d.png) to open characters

Work around: Just book mark and open the spell, monsters etc directly.

As far as main menu items go, it is a Single page app and this will not be implemented.

**Comment by kamander** [comment]
![image](https://user-images.githubusercontent.com/38440493/58053288-16522780-7b25-11e9-88f0-98c85a784c80.png)
This is great. Could you put that, as well as the Print button, on the Parties page as well?
