### ISSUE TITLE
Appearance and Name Options?

### ISSUE THREAD

**Issue by Vethar** [Orcpub/orcpub#183]
Could you include an option to fill out, the character name and appearance options (height, weight, skin, etc)?
It's no fun to have to fill out these by hand, every time, your character levels up.

**Comment by DivertedCircle** [comment]
There is already a tab devoted to this on the website.

![image](https://user-images.githubusercontent.com/26470570/58602003-5feaf280-8248-11e9-9ef8-19306a484d19.png)
