### ISSUE TITLE
Homebrew Sorcerer Spell not appearing on Sorcerer Spell List

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#227]
**Describe the bug**
The new spell, Mind Sliver, in the UA - Sorcerer & Warlock is appearing correctly on the Warlock and Wizard spell lists but isn't appearing on the Sorcerer or Sorcerer (Divine Soul) spell lists

**To Reproduce**
1. Upload the file at **https://drive.google.com/open?id=1mrmtkKHUW1BStv9CONemuYkUFM2xF1co**
2. Create a new Sorcerer character and look at the spells tab. Mind Sliver does not appear as an option in the cantrip section.
3. Repeat step 2 with a new warlock character and a new wizard character. Mind Sliver appears correctly on both lists.

**Expected behavior**
Mind Sliver should appear on all three lists.

**Comment by marloso2** [comment]
I'm struggling to recreate the issue on my end. I'm uploading the file with no edits but the spells shows up for me with no issues otherwise

**Comment by DivertedCircle** [comment]
It seems to be working fine for me on a different computer as well. I'll try a CTRL+F5 on my home computer later and see if that rectifies the problem.

**Comment by DivertedCircle** [comment]
Finding this is happening again now, with new spells. The spells in Grimlore's Grimoire (attached) are not loading for sorcerers.
