### ISSUE TITLE
Top menu bar doesn't scroll away on Firefox Mobile

### ISSUE THREAD

**Issue by moberemk** [Orcpub/orcpub#230]
**Describe the bug**
When viewing the web app on Firefox and Safari Mobile for iOS, the top bar containing the menu bar, bookmarks, tabs, etc, fails to disappear when scrolling down as other websites do.

**To Reproduce**
1. Open any part of the mobile on Firefox Mobile for iOS (latest version)
2. Scroll down

**Expected behavior**
Expected behavior is that the top bar should disappear (for reference, view other sites such as [Reddit](https://old.reddit.com))

**Smartphone (please complete the following information):**
 - Device: iPad Pro 11"
 - OS: iOS 12.4
 - Browser Firefox, Safari
 - Version Both latest

**Comment by datdamnzotz** [comment]
I took a look at this on a iPhone and iPad with Safari, and the site provides the menu's as expected.
@moberemk can you provide some screen shots?

**Comment by moberemk** [comment]
The menu is there yes, my issue is that the menu stays there--ideally the browser chrome menus should vanish during scroll to maximize screen real estate dedicated to the character sheet. This might make more sense to put together as a video demo than a screenshot; I'll see about putting one together if you can't repro the behaviour.

**Comment by Pireax** [comment]
I think this issue has now been resolved with #415 (maybe before)

**Comment by moberemk** [comment]
Yep, looks fixed now. Thanks!
