### ISSUE TITLE
Natural Armor shouldn't stack with Barbarian's Unarmored Defense

### ISSUE THREAD

**Issue by codeGlaze** [Orcpub/orcpub#235]
Natural Armor and Unarmored Defense are currently stacking for users.

We need to devise a way to prevent that.

**Comment by DivertedCircle** [comment]
Specifically, the feature in the screenshot is stacking with both the Barbarian's and the Monk's unarmored defense features.

![image](https://user-images.githubusercontent.com/26470570/65099633-df7e0800-d984-11e9-956c-b0756d88594b.png)

**Comment by DivertedCircle** [comment]
This is also happening with the Sorcerer Draconic Bloodline subclass.
