### ISSUE TITLE
Kobold doesn't allow options for languages

### ISSUE THREAD

**Issue by spexguy1** [Orcpub/orcpub#236]
**Describe the bug**
When I tried to create my Kobold ranger, there was an error on the tab where you select languages. I created another Kobold character to try to reproduce the issue, and there was still an error.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [2.5.0.2]

**Additional context**
Languages appeared after closing and re-opening the browser after some time had passed. Common not among them.

**Comment by DivertedCircle** [comment]
What source file are you using for the Kobold race?

**Comment by spexguy1** [comment]
> 
> 
> What source file are you using for the Kobold race?

The material is Volo's Guide to Monsters, I believe. I'll have to find the specific file when I get back home.

**Comment by datdamnzotz** [comment]
Orcbrew specific, please contact the author of the file.
