### ISSUE TITLE
Rar.'s Telepathic Bond absent from Wizard spell Selection

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#237]
**Describe the bug**
The spell 'Rary's Telepathic Bond' (shortened to Rar.'s Telepathic Bond for some unknown reason on the website) does not appear as a selectable spell for Wizards upon reaching 9th level and accessing 5th level spells.

**To Reproduce**
1. Create a wizard character.
2. Set it's level to at least 9.
3. Go to the spells tab.
4. Rar.'s Telepathic Bond is missing.

**Expected behavior**
Rar.'s Telepathic Bond should appear on this list as a selectable option.

![image](https://user-images.githubusercontent.com/26470570/65694303-e2d35c80-e032-11e9-859e-4724edabc3ca.png)

**Comment by LumaDevelopment** [comment]
`:wizard
   <spell lists for levels 1-4>
    5
    [:animate-objects :bigbys-hand :cloudkill :cone-of-cold
     :conjure-elemental :contact-other-plane :creation :dominate-person
     :dream :geas :hold-monster :legend-lore :mislead :modify-memory
     :passwall :planar-binding :scrying :seeming :telekinesis
     :teleportation-circle :wall-of-force :wall-of-stone],`

The spell seems to be missing in [the spell list above, which is the current source](https://github.com/Orcpub/orcpub/blob/develop/src/cljc/orcpub/dnd/e5/spell_lists.cljc). The spell does exist in [this file](https://github.com/Orcpub/orcpub/blob/develop/src/cljc/orcpub/dnd/e5/spells.cljc), though.

EDIT: I've made a [pull request](https://github.com/Orcpub/orcpub/pull/238) that may resolve this issue.
