### ISSUE TITLE
Races with cantrips break right hand spell view

### ISSUE THREAD

**Issue by codeGlaze** [Orcpub/orcpub#239]
On DMV (not OP2 for some reason), races with cantrips break the "Details" view when combined with the Paladin class.

Verified with Aasimar, Water Genasi and a custom race.

I'm not sure what we've changed from the initial fork to cause this.

**Comment by datdamnzotz** [comment]
To reproduce
Add custom race with 1 or more cantrips.
Create new Paladin with the custom race at lvl 1.

On the right display screen
Switch between equipment and spells

You will receive:
![image](https://user-images.githubusercontent.com/3913859/66141081-6277a300-e5c0-11e9-8269-5b4bed11bbaf.png)
And the right hand edit screen spells, features, equipment will not display.

**Comment by datdamnzotz** [comment]
Looks like merge #197 introduces this bug.
![image](https://user-images.githubusercontent.com/3913859/66141323-bb473b80-e5c0-11e9-9ccb-453740c799ec.png)

**Comment by datdamnzotz** [comment]
@KingMob looks like we bumped react and other things to bring in the react debug window... any ideas here?
![image](https://user-images.githubusercontent.com/3913859/66141537-12e5a700-e5c1-11e9-82a3-5e7eef2382e9.png)
