### ISSUE TITLE
Dueling Fighting Style

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#249]
**Describe the bug**
Dueling Fighting Style does not apply its bonus damage to one-handed weapons listed in the combat tab.

**To Reproduce**
1. Create a Fighter character of at least level 2.
2. Select Dueling as your Fighting Style.
3. Equip a one handed weapon.
4. See damage does not increase.

**Expected behavior**
A +2 bonus should be applied to damage with the one handed weapon.

**Comment by datdamnzotz** [comment]
Possibly expand this to Fighting Style Creator for fighters, rangers and paladins...
