### ISSUE TITLE
Reorganize Spell Builder Page

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#255]
**Is your feature request related to a problem? Please describe.**
Currently the Spell Builder page is not laid out the same as a typical spell block from a WotC book is.

**Describe the solution you'd like**
Reorganize the Spell Builder page to reflect the same order as the WotC standard.

**Additional context**
I propose the following changes:

- Move 'Add This Spell to Which Class Spell Lists?' below 'Description'.
- Move the 'Ritual' and 'Requires Attack Roll' check boxes to the same line as 'Level' and 'School'.
- Shrink the 'Components' text box and move 'Duration' to the same line.

**Comment by codeGlaze** [comment]
I'm not sure what these really improve.
This seems like it would be much less usable on mobile as well as being less logical while building the actual spell.

**Comment by DivertedCircle** [comment]
It changes it to follow the same order as a spell block, making it much easier to create spells. As someone who has entered a lot of spells, it gets annoying having to look all over a spell block for the relevant information.

**Comment by codeGlaze** [comment]
```It changes it to follow the same order as a spell block,```
This is where I'm confused.
I made a small commit last night to move the one element that didn't match existing spellblock layout.

Can you attach a picture of the spellblock you're referencing? I was using the phb.

**Comment by DivertedCircle** [comment]
One image from the PHB and one from 5e.tools.

![image](https://user-images.githubusercontent.com/26470570/69157770-ac4e1700-0aa2-11ea-9898-c9bfffb1adf4.png)
![image](https://user-images.githubusercontent.com/26470570/69157799-b6701580-0aa2-11ea-9b7f-22e74497662f.png)

**Comment by codeGlaze** [comment]
My latest PR moves duration below components where it should be.

Is there an actual benefit to moving the class list to the bottom instead of with the other meta-information at the top?

**Comment by DivertedCircle** [comment]
Other than following a logical order or creating the spell first, then assigning it to classes? Probably not.

**Comment by datdamnzotz** [comment]
@marloso2 you going to do a pull request for this?
