### ISSUE TITLE
Single non-srd class spells

### ISSUE THREAD

**Issue by TheWanderingLynx** [Orcpub/orcpub#257]
**Describe the bug**
I'm putting in a homebrew class and I cannot make spells only for that specific class if it doesn't also have at least one SRD class included.

**To Reproduce**
Make a new class, with spellcasting ability.
Create a new spell.
New class doesn't appear in class select options.
Spell cannot be saved if no class selected.

**Expected behavior**
Custom classes should appear in spell creator.

**Comment by DivertedCircle** [comment]
I don't believe there's a way for custom classes to appear how you want them to. What you need to do is create the spell first and assign it to any class. Then, go into your custom class in the Class Builder and assign them the spell you created.

**Comment by codeGlaze** [comment]
Resolved?

**Comment by datdamnzotz** [comment]
No response. Closing.
