### ISSUE TITLE
Unable to Select Monk Class 

### ISSUE THREAD

**Issue by silverphantom6005** [Orcpub/orcpub#259]
**Describe the bug**
When selecting the monk class for a character the website creates a black screen instead of presenting any information. After refreshing the tab or logging off and back on, any attempts to go to Class/Level will result in the same clear, black screen. You are unable to remove the monk class and all other transitions work fine, 

**To Reproduce**
1. Go to 'Class/Level'
2. Click on 'Monk'
3. See Error 
4. Refresh, Reload, or Log Off 
5. Login 
6. Go to 'Class/Level'
7. Still, see Error

**Expected behavior**
When clicking on Class/Level and selecting Monk I expected to see the typical prompts when selecting a class. Specifically for Monk, there should be the Class/Level section, a Hit Points section, and a Mosaic Tradition section. 

**Screenshots**

![image](https://user-images.githubusercontent.com/57273857/68350826-9f5b1c00-00cf-11ea-9ea1-7bad705c7381.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome and Firefox]

**Additional context**
This problem so far has only been apparent in the Monk class and has happened to me more than once within the past month. Whatever the bug is I believe may have simply been fixed overtime form previous occurrences because one day everything went back to normal without any input or compliant only to return again days later.

**Comment by codeGlaze** [comment]
Looks like your custom content is causing an error.

1. Export your content
2. Test it by uploading it to the site using an incognito browser.

Report back if the export *doesn't* re-upload properly.

**Comment by silverphantom6005** [comment]
Thanks for the response! Based on your instructions, I learned whatever is happening is some sort of content error since I continue getting the black screen whenever I have my exported content enabled. Everything appears as it should by AL standards when my exported content is disabled. 

However, this essentially means I'm unable to use the Monk class whenever I need exported content for any class since Monk is the only class that causes this error. I need all of my content enabled for the other classes work.

**Comment by codeGlaze** [comment]
Hop into the discord server and one of us will try to find the error in the file for you.
Just a heads up, that could take 5 minutes or 24 hours depending on who is available and how much content we have to sift through. :P

**Comment by codeGlaze** [comment]
Issue: Bug in a local file causing domino effects.
Fixed, I think?
