### ISSUE TITLE
Class/Level

### ISSUE THREAD

**Issue by jdsy27** [Orcpub/orcpub#271]
As I was going through the character builder I chose to edit one of my characters since they leveled up. So I go to the Class/Level underneath the options section and the website text disappears and all I see is the background. Reloading the page brings everything back, but once I click on Class/Level all the text disappears. The thing is, is that it only happens for some of my characters that I have created with Character creator. Does anyone else have this problem? And if so how do you fix it?

![Annotation 2019-12-01 151831](https://user-images.githubusercontent.com/58404749/69922111-ff827b00-144d-11ea-837e-afcac94c483e.png)
![Annotation 2019-12-01 151832](https://user-images.githubusercontent.com/58404749/69922123-250f8480-144e-11ea-8204-76124d7de70c.png)

I am using this currently
 - OS: Windows 10
 - Using Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by marloso2** [comment]
By "some of [your] characters" what do you mean? Are they all Battle Master characters? Are they all Fighters?

**Comment by DivertedCircle** [comment]
I think what Marloso is getting at is that it sounds like you have a bugged orcbrew. I recommend updating all your files from The List and seeing if the issue persists.

**Comment by marloso2** [comment]
Yeah, just wanted to try to confirm that before giving any advice that may or may not be helpful 😋

**Comment by jdsy27** [comment]
Thanks I'll try updating the files.

**Comment by jdsy27** [comment]
Where do you get your files?
Cause I got mine from the OrcPub Checklist

**Comment by codeGlaze** [comment]
1. How old is your homebrew collection?
2. How old are those characters?
3. What levels are those characters?
   1. Classes?
   2. Subclasses?

**Comment by codeGlaze** [comment]
1. How old is your homebrew collection?
2. How old are those characters?
3. What levels are those characters?
   1. Classes?
   2. Subclasses?

**Comment by DivertedCircle** [comment]
The main file I would recommend updating is UA - Fighter if you have it. There was an issue with the Sharpshooter subclass awhile back that was causing a similar bug as the one you're experiencing.

**Comment by jdsy27** [comment]
Will do

**Comment by jdsy27** [comment]
I believe the problem that was making the bug occur was a file that I was trying to create myself based off of Zow's Arcane Artillery.

**Comment by jdsy27** [comment]
It is crying shame that I can't implement it into the Dungeon Master's Vault and no one has yet made an .orcbrew of it.

**Comment by codeGlaze** [comment]
Uh... what?

**Comment by jdsy27** [comment]
So the thing was is that I was trying to create a .orcbrew based off of Zow's Arcane Artillery and it is more than likely that somewhere along the line that file was corrupted and so it was giving me grief by giving me the previous problems.

**Comment by jdsy27** [comment]
But now as I go back to edit these characters with some updated files I'm using from the OrcPub checklist the website is now updating itself whilst erasing the content I just imported.

**Comment by jdsy27** [comment]
Along with OrcPub not recognizing the "all-content.orcbrew" that I create after pressing the export-all button.

**Comment by DivertedCircle** [comment]
Please try to keep your comments to a single post where possible. The all content export issue and your browser clearing files are both known issues. See the #faqs channel on the Discord server.

**Comment by jdsy27** [comment]
Thank you, I didn't know there was a Discord for this.

**Comment by datdamnzotz** [comment]
Closing due to bug with orcbrew and not Orcpub itself.
