### ISSUE TITLE
Login Screen does not autofill saved forms or recognize Enter key

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#277]
**Describe the bug**
Login Screen does not autofill saved forms or recognize Enter key

**Expected behavior**
Login screen should autofill both username and password on both Chrome and Firefox if that option is enabled.

**Screenshots**

![image](https://user-images.githubusercontent.com/26470570/70164363-43f45d80-167e-11ea-901a-5500ff7b5da9.png)

**Comment by codeGlaze** [comment]
Hasn't this already been raised?

**Comment by codeGlaze** [comment]
#84 is the same thing

**Comment by datdamnzotz** [comment]
Duplicate of #84 closing.
