### ISSUE TITLE
Combat tracker sets generators icon as active as well 

### ISSUE THREAD

**Issue by tombomb** [Orcpub/orcpub#306]
**Describe the bug**
if you go to the combat tracker the generators icon is also set to active

**To Reproduce**
go to https://www.dungeonmastersvault.com/pages/dnd/5e/combat-tracker
see that both encounters and generators are light up

**Expected behavior**
only encounters lights up

**Screenshots**

![image](https://user-images.githubusercontent.com/544509/74021668-efb17680-4969-11ea-83bf-37cd5e1d1b08.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome 
 - Version 79

**Comment by datdamnzotz** [comment]
DMV specific UI, Fixed Closing
