### ISSUE TITLE
Form fillable pdf duplicates prepared spaces on multiple sheets

### ISSUE THREAD

**Issue by Kyosji** [Orcpub/orcpub#323]
Bug I've noticed.  On the editable sheets you download after creating a character, if you have multiple pages of spells, when you click a bubble on one page, an identical bubble on the next page also selects, when you deselect, the other deselects.  Noticed it when I got yelled at for having 10 prepared spells when I know I didnt.

**Comment by datdamnzotz** [comment]
Please follow the template provided. 

Need OS and what editor your using to edit the pdf. I would suggest downloading acrobat reader and see if that fixes your issue.  Editing in FF or chrome doesn’t work

**Comment by Kyosji** [comment]
Windows 10, using adobe acrobat reader

**Comment by datdamnzotz** [comment]
Duplicate of #202 
Closing
