### ISSUE TITLE
Divine Soul Sorcerer missing the cleric spell options

### ISSUE THREAD

**Issue by ChaosHunter21** [Orcpub/orcpub#331]
hey there! while im choosing divine soul sorcerer, the cleric spell list should be available too, but unfortunately it is not. is there a way that u can fix it, cause it would solve a major problem. 
thanks a lot in advance!!

**Comment by codeGlaze** [comment]
DVS is not SRD and not part of the codebase.
If you're using Homebrew with the DVS you need to contact the creators of the file.

**Comment by ChaosHunter21** [comment]
Is there a way that I can at least add the spell list manually? Cause as I press edit to the DVS there isnt any option for that.

**Comment by codeGlaze** [comment]
The way I've seen people build it, the DVS has been built as its own Base class. Which should open up the ability to have cleric spells.

To be completely honest it's not something I've given much thought to personally.

You should join the discord server and ask the community there.

**Comment by DivertedCircle** [comment]
Sounds like you have a bad or incomplete version of the Divine Soul sorcerer. Join the discord and get the complete version that allows the choice of both sorcerer and cleric spells.

**Comment by ChaosHunter21** [comment]
Can u give a link or something cause im kinda new here.. Thanks!!

**Comment by DivertedCircle** [comment]
https://discord.gg/MHyfWvk

**Comment by ChaosHunter21** [comment]
Unfortunately I cant seem to find any version of DVS even at the discord server. Also how can I join all the channels such as the #orcbrew-requests??

**Comment by DivertedCircle** [comment]
DVS is in XGTE. Read the #faqs channel as was instructed when you joined the server and follow the instructions there.
