### ISSUE TITLE
Tomes don't increase the max value for a stat

### ISSUE THREAD

**Issue by PietroCasotto** [Orcpub/orcpub#332]
**Describe the bug**
A fiew month ago i?ve come across a "Tome of understanding" and i've decided to give it to my druid... The bug I'm facing right now is that i already have my Wis at 20 (max) bu the tome increase the value of the stat AND the maximum value for that stat, allowing me to reach 22 in wisdom (+6) this error desn't allow me to have the right numbers in all the app. IE: spells, TS, ToHit ecc are 1 oint lower of the real value

**Comment by codeGlaze** [comment]
Hm 🤔
But is it increasing appropriately anywhere?

Your description sounds like it increases something but that doesn't propogate to your relevant derived stats.

**Comment by PietroCasotto** [comment]
no, the problem is that it's not calculated anywhere... In my lv 17 druid I have wis 22 (+6), +6 proficiency and the staff of the woodlands. My magical toHit should be +14 but in the site is only +13, the DC should be 20 but it's 19. the prepared spells should be 23 but it's indicated 22, the skills and saving trows too. The problem is that my wisdom in the ability scores' section is only 20 and not 22 as it should be... I've set in the equipment page under the section "other magic items" the tome of understanding but it won't icrease my wisdom over 20

**Comment by datdamnzotz** [comment]
Confirmed bug, looks like the code caps at 21.
https://github.com/Orcpub/orcpub/blob/d6c74d4cae98527da71195cb34a0ae3bb587b216/src/cljc/orcpub/dnd/e5/character.cljc#L22-L22
