### ISSUE TITLE
The information for the weapon Sun Blade is wrong. For example, the Finesse property doesn't appear.

### ISSUE THREAD

**Issue by ivanmbur** [Orcpub/orcpub#334]
**Describe the bug**
The weapon Sun Blade does not behave properly.

**To Reproduce**
1. Create a Halfling Monk with higher Dex than Str
2. Equip Sun Blade
3. Finesse property of Sun Blade does not appear. In particular, the damage is still computed with strength.
4. Moreover, eventhough the Halfling monk has proficiency in shortswords, it doesn't have proficiency with the Sun Blade. 

**Expected behavior**
Since the Sun Blade has the finesse property it would compute attack and damage rolls with either Dex or Str, depending which is higher. Moreover, characters which have either proficiency in short or longswords should automatically be proficient in the Sun Blade. Finally, the damage type appears as slashing when it should be radiant.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Don't know.

**Additional context**
I believe that a big part of the problem is that Sun Blade has been programmed as a longsword. The Sun Blade is however not a long sword.

**Comment by DivertedCircle** [comment]
Please fill out the bug report form.

**Comment by ivanmbur** [comment]
Done!

**Comment by datdamnzotz** [comment]
Confirmed bug,
https://github.com/datdamnzotz/orcpub/blob/71cd296eceb437c496a4197d97da5d0bc979e543/src/cljc/orcpub/dnd/e5/magic_items.cljc#L2589-L2588

Should be applying ::modifiers when it isn't.

**Comment by codeGlaze** [comment]
Wondering if maybe changing `::item-subtype` from `longsword` to `sword?` might fix it.

**Comment by codeGlaze** [comment]
Figure out an elegant fix is going to take a bit.

There are multiple modifiers not working as intended. 🤔
