### ISSUE TITLE
Error on docker-compose up

### ISSUE THREAD

**Issue by 4sfaloth** [Orcpub/orcpub#341]
Hi all,

I'm trying to set-up a local orcpub development environment so I can work in a new feature (please see https://github.com/Orcpub/orcpub/issues/233). 

I tried to follow the instructions but I seem to get some connection error when. I am not entirely sure but I think it's trying to access a remote database and failing, please see attached image:

![orcpub-docker](https://user-images.githubusercontent.com/8202087/77365245-ae282f80-6d4d-11ea-8f48-d2cedb4831a8.PNG)

I am on Windows 10 using Docker

Any help would be appreciated. Thanks in advance

**Comment by datdamnzotz** [comment]
At a glance looks like it didn't connect to datomic.  https://github.com/Orcpub/orcpub/blob/develop/docker-compose.yaml make sure you have a password set for datomic.

**Comment by 4sfaloth** [comment]
> At a glance looks like it didn't connect to datomic. https://github.com/Orcpub/orcpub/blob/develop/docker-compose.yaml make sure you have a password set for datomic.

thanks for getting back to me.
I googled a bit and it seems "datomic" is some kind of database, probably where it stores the characters, etc... right?

I didn't change anything regarding that on the yaml so it still reads
```
  datomic:
    image: orcpub/datomic:latest
    volumes:
      - ./data:/data
      - ./deploy/transactor.properties:/datomic/transactor.properties
    restart: always
```
should I change anything in here? Do I need to install something else on my machine so I have a local database or something?

**Comment by datdamnzotz** [comment]
Correct.  Datomic is a no-SQL type database.  You are making the datomic container read from ./deploy/transactor when you don't need to.  This is settings file for Datomic itself. (host name, Memory etc..)

The datomic image transactor file is modfied during the build with the right settings via https://github.com/Orcpub/orcpub/blob/develop/docker/datomic/Dockerfile

If you are changing the password - you need to update both Datomic and the Orcpub environment variables. 
https://github.com/Orcpub/orcpub/blob/develop/docker/datomic/Dockerfile#L21
and
https://github.com/Orcpub/orcpub/blob/develop/docker-compose.yaml#L16

There are a couple ways you can run Orcpub.  
1) From the canned ready to go prebuilt images that are built on docker hub. To do this use the  
https://github.com/Orcpub/orcpub/blob/develop/docker-compose.yaml example file.  You can do a `docker-compose up` and this will pull these images from docker hub, and it will launch the site.

2) Build your own local containers from the source.  
To do this use the https://github.com/Orcpub/orcpub/blob/develop/docker-compose-build.yaml example file. You have to rename this file to docker-compose.yaml then do a `docker-compose up --build`  and it will build the containers from the local source files on your machine.

3) https://github.com/Orcpub/orcpub#without-docker

Best guess, you are on the wrong branch or your develop branch is not current with the one in github.  
To update it - cd to your local copy that you cloned, do a

`git pull origin develop`
`git checkout develop -f`

The datomic section now should look like:
```
datomic:
    image: orcpub/datomic:latest
    volumes:
      - ./data:/data
      - ./logs:/logs
    restart: always
```

**Comment by 4sfaloth** [comment]
@datdamnzotz thank you for your help. Indeed the problem was my repository not being up-to-date (I'd forked it some weeks ago). I have now managed to run orcpub both using the prebuilt image and by building the containers here. Tomorrow I'll try to start playing around with the clojure script code :)
