### ISSUE TITLE
The website doesn't show me all the spells I can learn as a warlock.

### ISSUE THREAD

**Issue by JokerJ05** [Orcpub/orcpub#356]
**Describe the bug**
I am playing a Sorlock with 9 levels of warlock under my belt. I looked a bit further to see what kind of 6th level spells would become available for me. The problem is that I was only given 7 options as possible new spells. While I know I should have te option of choosing between 15 spells. Could this please be fixed?

**To Reproduce**
1. Create a 11th level Warlock.
2. Go to the bottem of the 'spells' section.
3. Now you see 'Mystic Arcanum: Spell Level 6'.
4. Now I only see the spells: 'Circle of Death', 'Conjure Fey', 'Create Undead', 'Eyebite', 'Flesh to Stone', 'Mass Suggestion', 'True Seeing'.

**Expected behavior**
I expected to see 15 spells instead of 7.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome
 - Version: 80.0.3987.149 (Officiële build) (64-bits)

**Additional context**
This problem is not just for spell level 6. The Mystic Arcanum options for spell level 7 only show 4 spells, instead of 6, level 8 shows 5 instead of 6 and level 9 also only shows 5 spells instead of 6.
Could you guys please look into this?
In any case, thank you for reading this. Hope you have a nice day.

**Comment by DivertedCircle** [comment]
This is the same issue as #126. Requires a fix that would allow flagging homebrew spells as Mystic Arcanum and rolling them into the existing list.
