### ISSUE TITLE
Belt of Dwarvenkind

### ISSUE THREAD

**Issue by Ember-Adventures** [Orcpub/orcpub#358]
Belt of Dwarvenkind isn't listed at all on the website, having to input a custom item the manually update the affected information is a pain.

**Comment by codeGlaze** [comment]
Is the belt SRD?

**Comment by DivertedCircle** [comment]
It is, and I can confirm it's missing.
https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf
![image](https://user-images.githubusercontent.com/26470570/79057800-abb94700-7c22-11ea-9951-7a9065ce04a0.png)
