### ISSUE TITLE
Class Issue

### ISSUE THREAD

**Issue by doublernr** [Orcpub/orcpub#360]
**Describe the bug**
Home-brewed a class. Glitched a little but still worked. Clicked back into character builder worked for a few seconds before it went blank. Cannot access character builder at all. Can't figure out how to delete home-brewed class either.

**To Reproduce**
1. Choose Race
2. Homebrewed Class (UA Sidekick)
3. Set to Level 15
4. See error?

**Expected behavior**
I expected it to be able to access character builder or at least allow me to reset the character builder.

**Screenshots**
It's completely blank

**Desktop (please complete the following information):**
 - Browser [safari]

**Additional context**
Not sure.

**Comment by doublernr** [comment]
Figured out how to delete class and the issue cleared up.

**Comment by codeGlaze** [comment]
Thank you for getting back to us on this. Closing because you fixed your own issue 😉
