### ISSUE TITLE
Unable to paste in character sheet.

### ISSUE THREAD

**Issue by GGNORE12** [Orcpub/orcpub#365]
**Describe the bug**
So I was playing a homebrewed match, using an artificer. I levelled up to level 3 and asked the DM if he allows me to attach modifications to my gun following the D&D wiki for Artificer, Gunslinger Variant (5e Class). He said sure but I have to add it under my traits so that he can see it and I won't change it in the middle of the campaign. Fair enough, so I just did that, or tried to. I opened up my character sheet go to wiki and try to copy and paste the modifications I choose and put it on the the character sheet. Blank, nothing was added. I waited for awhile, expecting it to appear soon. 10 minutes nothing happened. I reloaded the page and did it again, still nothing. I used 'paste in plain text'. Nope nothing. I switched to Microsoft edge, still nothing. Thinking that I might have not copied the text I opened my word document and tried paste. There it is the gun modification's name and description. I tried to paste in the character sheet again, nothing. I tried copying sentences from the character sheet to see if copy & paste is disabled. Nope, the copy function is just fine. After trying 8 or so time I gave up and restarted the computer to try again. Still nothing. I can still type on the character sheet so I did just that but I am writing this to know if anyone else also have this problem or is it just me? If it is just me what should I do?

**Expected behavior**
I expect having the ability to paste additional information into the character sheet.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 Home
 - Chrome
 - Version 81.0.4044.122
--

**Comment by datdamnzotz** [comment]
Could be a couple things happening here,  Impossible to say without more information.
1) Your not logged into the account that owns the character.  You can not modify characters that you don't own.
2) The source that you are copying from has invalid special characters in it.

Login to the account that owns the character, and copy the source into notepad, then copy paste it from notepad into the site it should work fine.  This normally happens on backticks `  crlf's or other special characters.

**Comment by GGNORE12** [comment]
Thank you for your comment. I need to clarify that my character is first made by myself while logged in at Dungeon Master's Vault website. I also have the ability to copy and paste a week ago and I haven't updated anything ever since. As for copying and pasting using the notepad, I have just tried. However, I am still unable to copy and paste it. I am able to copy anything on a character sheet and put it on a word doc and it still comes out as English characters. However, if I try to paste anything to the character sheet. No matter what is the source, it is unsuccessful.

**Comment by datdamnzotz** [comment]
> **Screenshots**
> If applicable, add screenshots to help explain your problem.

...Also, your login, the source your trying to save, and where in the application you are having issues. which text box you are updating...

**Comment by codeGlaze** [comment]
@GGNORE12 

Are you downloading *then* opening the PDF in acrobat or a similar reader?

Google's PDF viewer doesn't handle fillable forms well and often doesn't save data.

**Comment by GGNORE12** [comment]
Well I am using the Google PDF version because it is the only version that allows me to edit the character sheet for free.

**Comment by codeGlaze** [comment]
Adobe PDF Viewer is free.

**Comment by datdamnzotz** [comment]
Known issue in Chrome/FF on the browser side, use Acrobat 

Closing
