### ISSUE TITLE
Knowledge Domain does not allow 2 languages to be selected at first level

### ISSUE THREAD

**Issue by BillyKings173** [Orcpub/orcpub#366]
**Describe the bug**
Knowledge Domain selection does not allow for selection of 2 additional languages at first level.

**Expected behavior**
Blessings of Knowledge
At 1st level, you learn two languages of your choice. You also become proficient in your choice of two of the following skills: Arcana, History, Nature, or Religion.

Your proficiency bonus is doubled for any ability check you make that uses either of those skills.

**Comment by DivertedCircle** [comment]
Knowledge Domain is not a subclass that is baked into the site. Either you have an error in your orcbrew file, or it is a limitation of what can be built using orcbrews.

**Comment by andyd4193** [comment]
This issue effects me to in exactly the same way

**Comment by DivertedCircle** [comment]
As mentioned above, this is not an issue with DMV, it is an issue with your orcbrew file.
