### ISSUE TITLE
Artificer Spellcasting

### ISSUE THREAD

**Issue by xdragonhaterx** [Orcpub/orcpub#370]
The Artificer Spellcasting doesn't work.
You don't get to chose any spells at first level, only cantrips.
I know the Artificer has a different Spellcasating system than other classes (different than other half casters), but I don't think it is that much harder to implement.
number of known spells = INT mod + half level if level > 1 (normally rounds down), 1 if level = 1

**Comment by DivertedCircle** [comment]
This is a duplicate of https://github.com/Orcpub/orcpub/issues/272.
