### ISSUE TITLE
Manual Editing Options

### ISSUE THREAD

**Issue by xdragonhaterx** [Orcpub/orcpub#371]
I would like it if there was an option (a new slide in character builder) where you could manually add/edit proficiencies and other stuff (like AC, speed...). Basically manually edit any value of a character. 
As well as the possibility to edit your number of spell slots, number of known spells, prepared spells and available spells. Basically manually edit your spells and anything concerning spells.

I suggest this because there are many class, subclass, race, subrace and background features that give you stuff (or give you the possibility to chose), but the site doesn't automatically implement them (meaning you have to find a way to chose them somewhere, usually by editing a background), as well as there not being a way to add proficiencies and other stuff you might get/learn during the campaign.

I know implementing all of this would be really hard and would take a lot of time, but I hope someone will be willing to do it as it will make Dungeon Master's Vault (orcpub) a lot better.

**Comment by datdamnzotz** [comment]
PDF pretty much provides that functionality today.  No need to bring it into the Editor, the editor scope is for character creation with rules. If you want to free form it, there is always the PDF
