### ISSUE TITLE
Add roll buttons for skill checks

### ISSUE THREAD

**Issue by datdamnzotz** [Orcpub/orcpub#372]
**Is your feature request related to a problem? Please describe.**
Add buttons to skill checks and create new buttons for attack and damage. 

Something like:
![image](https://user-images.githubusercontent.com/3913859/80766523-da7c5c00-8b02-11ea-899b-c26c11fde558.png)

**Comment by DivertedCircle** [comment]
The new buttons for damage rolls are incorrectly using the bonus to hit.
