### ISSUE TITLE
Trying to share character sheets with Orcbrew don't display in link

### ISSUE THREAD

**Issue by Baxmann** [Orcpub/orcpub#374]
**Describe the bug**
When sharing a character from the character builder, there is a link button that allows other players to see their character. Unfortunately, if the character has Orcbrew, like for instance a blood hunter, those features and abilities won't display for them unless they import in all the Orcbrew.

**To Reproduce**
1. Create a character that has any type of Orcbrew. It is most notable with a class like Blood Hunter.
2. Go to the character builder and click the open button.
3. To the left of the _Edit_ button is a WWW. Click that and it will create a link to the character.

**Expected behavior**
Abilities, Features, and even proficiencies don't show properly.

**Screenshots**
My Side
![my side](https://user-images.githubusercontent.com/34702584/80832833-01926680-8bb3-11ea-86e5-d93b8b122dba.png)
Link Side
![players side](https://user-images.githubusercontent.com/34702584/80832841-048d5700-8bb3-11ea-95de-3df6cb946322.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 2.5.0.10

**Comment by datdamnzotz** [comment]
It is how the site is architected.  The orcbrew files are the data for the characters.
Share the orcbrew file, or create a PDF to share characters.
