### ISSUE TITLE
email verification link not working

### ISSUE THREAD

**Issue by MilleIT** [Orcpub/orcpub#375]
**Describe the bug**
Whenever i click on the verification link received in the verification mail it sends me to blank this is not working page and gives me a http error 400. This in turn prevents me from verifying my email and thus prevents me from logging in.

**Comment by datdamnzotz** [comment]
Verification links only work once.
So need more information to trouble shoot futher.
- are you getting this error in a self hosted environment or on dmv?
- what's the email address/account you are using?
- your ip address myipaddress.com

**Comment by datdamnzotz** [comment]
No response logs have rolled. - closing.
