### ISSUE TITLE
Add Background and Alignment to dynamic character sheet

### ISSUE THREAD

**Issue by ashf** [Orcpub/orcpub#395]
Currently the only way to see a character's background and alignment is via the edit screen or exporting as a pdf. Ideally they'd show up here:

![image](https://user-images.githubusercontent.com/6597733/82344881-96be9900-99c2-11ea-84b8-07f022bf0f01.png)

**Comment by sudonotpseudo** [comment]
I'll try to knock this shortly.

**Comment by datdamnzotz** [comment]
Character summary screen - "Characters" (/pages/dnd/5e/characters) - is built via a call to /dnd/5e/character-summaries which returns EDN list of characters

Via route
https://github.com/Orcpub/orcpub/blob/a6a3a9c2bc59c9d49784756fa2f7fceb2ea3ecce/src/cljc/orcpub/route_map.cljc#L153

Via map
https://github.com/Orcpub/orcpub/blob/a6a3a9c2bc59c9d49784756fa2f7fceb2ea3ecce/src/clj/orcpub/routes.clj#L1032

character-summary-list or character-summaries produces:

```edn
[{:db/id 17592186470293, :orcpub.dnd.e5.character/classes [{:db/id 17592232375062, :orcpub.dnd.e5.character/level 14, :orcpub.dnd.e5.character/class-name "Paladin", :orcpub.dnd.e5.character/subclass-name "Oath of Vengeance"}], 
```
character-summary-list has a Datomic query I can't seem to figure out how to include the characters alignment and background.
https://github.com/Orcpub/orcpub/blob/8d04b600ace6147fe1a5fa39cc44b1fb9ff96159/src/clj/orcpub/routes.clj#L783-L808

Help needed to populate the character list with alignment and backgound (/pages/dnd/5e/characters)
![image](https://user-images.githubusercontent.com/3913859/94703031-a8fafd00-02fb-11eb-92e2-0f658cab3143.png)

**Comment by datdamnzotz** [comment]
Related #467
