### ISSUE TITLE
Optional Character Sheet Booklet

### ISSUE THREAD

**Issue by datdamnzotz** [Orcpub/orcpub#396]
**Is your feature request related to a problem? Please describe.**

Hey I found this really cool character sheet on reddit, it's probably a hard now but would it be possible to build this into your amazing website? 

https://www.reddit.com/r/DnD/comments/grrdpi/oc_i_created_a_character_sheet_booklet_link_in/?utm_medium=android_app&utm_source=share

**Comment by Jessomadic** [comment]
I am making new CS I can see what I can do. What is the size of the book?

**Comment by datdamnzotz** [comment]
Copyrighted product - can't add to our code
