### ISSUE TITLE
Character sheet not showing proficiencies always

### ISSUE THREAD

**Issue by Cjen1** [Orcpub/orcpub#400]
**Describe the bug**

**To Reproduce**
1. Go to https://www.dungeonmastersvault.com/pages/dnd/5e/characters/17592223528466?frame=true

**Expected behavior**
Proficiencies shown in vivaldi desktop (chromium), but not chrome on android.

**Screenshots**
![image](https://user-images.githubusercontent.com/11444677/84683479-2b1f0b80-af2f-11ea-9bc2-586eb5fb7735.png)

**Desktop (please complete the following information):**
 - OS: Android and Arch Linux
 - Browser chrome and vivaldi respectively
 - Version [

**Smartphone (please complete the following information):**
 - Device: moto g6
 - OS: Android

**Additional context**

**Comment by Cjen1** [comment]
Further looking into this, it appears to be a reference issue. When I load it up online (in another browser) the custom races etc doesn't persist, and hence although the entries still exist in the character info, their effects don't exist.

**Comment by datdamnzotz** [comment]
Did you load the orcbrew that was used to create the character the on both browsers?  

You need to always use the orcbrew that was used to create the character.

**Comment by Cjen1** [comment]
Yes it was not showing before I had loaded the orcbrew up on both browsers (but now that I have it loaded, it is working as expected). 

Surely the relevant parts of the orcbrew could be stored alongside the character? For example by 'flattening' the data-structure such that all references are incorporated? That would then make it substantially easier to share and store character sheets (especially if custom items/traits/spells are used and don't have to be manually shared around).

**Comment by codeGlaze** [comment]
Items are saved to a user's account.

The decision to keep references to the data instead of the actual data is brought up every couple months. But ultimately it saves the project legal headaches as far as we're aware.

Characters can always be printed to PDF and shared that way.

Having a copy of only character-relevent data for web-linking is still a team debate.

**Comment by Cjen1** [comment]
@codeGlaze I was slightly expecting it to be a legal issues (though I'd have expected safe harbor to protect you regarding references to user data which isn't globally accessible). Thanks for letting me know!
