### ISSUE TITLE
Imported Content Files won't stay

### ISSUE THREAD

**Issue by CacctusMan** [Orcpub/orcpub#403]
Whenever I upload a homebrew content file, it disappears immediatly after I refresh the page. Only the first file I uploaded from a blank slate stays.

I.e. I open up DMV, go into homebrew content list, which is empty, upload File A, and then upload File B. When the page is refreshed, only File A remains. If I delete both files and upload file B, same thing happens, only this time File B remains.

If I try to export it all into an allcontent file and try, the allcontent file doesn't stay at all

**Comment by DivertedCircle** [comment]
From the #faq channel on the Discord server: 
![image](https://user-images.githubusercontent.com/26470570/85412278-a6338380-b526-11ea-8047-3666e7983d17.png)
