### ISSUE TITLE
Bug: Double Longsword entry in Weapon Proficiency selector

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#409]
**Describe the bug**
Longswords are showing up twice as an option in the Weapon Proficiencies section of the Race Builder and Subrace Builder.

**To Reproduce**
1. Go to the Race Builder or Subrace Builder.
2. Scroll down to the Weapon Proficiencies section.
3. See error.

**Expected behavior**
There should only be one entry.

**Screenshots**
![image](https://user-images.githubusercontent.com/26470570/86523082-2d84cf00-be24-11ea-9664-2dbd4d5eb977.png)

**Additional Information**
Suspect it's related to the fix applied for #334.

**Comment by codeGlaze** [comment]
It's not a bug. It was a messy patch to make the Sun Sword work correctly.

**Comment by DivertedCircle** [comment]
That still means it's a bug that needs to be fixed.

**Comment by datdamnzotz** [comment]
See comments in #411
