### ISSUE TITLE
Add Missing CRs to monster creator

### ISSUE THREAD

**Issue by codeGlaze** [Orcpub/orcpub#41]
There are a handful of CRs missing in the monster builder, they should be added.

**Comment by datdamnzotz** [comment]
More information: 
On the /pages/dnd/5e/monster-builder
CR list is missing 18, 25, 26, 27, 28 and 29 missing from the drop down selection

![image](https://user-images.githubusercontent.com/3913859/51943611-21971100-23d7-11e9-9e2a-3441fde20338.png)

Appears to be build by [labeled-dropdown](https://github.com/Orcpub/orcpub/blob/develop/src/cljs/orcpub/dnd/e5/views.cljs#L6056)
