### ISSUE TITLE
Menu bar overflows on mobile devices

### ISSUE THREAD

**Issue by Pireax** [Orcpub/orcpub#413]
**Describe the bug**
The menu bar is not fully within the page, while it is accessible by scrolling it looks off.

**To Reproduce**

1. Use a mobile device
2. Load any page of the website

**Expected behavior**
Menu bar is fully within the bounds of the screen, all buttons are accessible and scrolling 'out' of the page is not possible.

**Screenshots**
![image](https://user-images.githubusercontent.com/11289656/87089724-2bad7800-c237-11ea-90ab-4c3420167d91.png)

**Smartphone (please complete the following information):**

 - Device: Xiaomi Mi 9T
 - OS: Android 10
 - Browser: Chrome
 - Version: 83

**Comment by Pireax** [comment]
Most likely this problem was introduced due to the addition of the Patreon button, maybe a solution would be to move this (on mobile) next to the Dungeon Master's Vault header?

**Comment by codeGlaze** [comment]
I don't have that problem. But the page does move like elements aren't fitting properly. 👍

**Comment by Pireax** [comment]
Yeah it's probably only an issue on smaller windows, the browser on my phone uses a width of 393 px to display the page but also some more known devices probably have this issue, for example the iPhone X uses a width of 375 px. it's also reproducible on chrome devtools with the mobile viewport.

**Comment by datdamnzotz** [comment]
It probably was introduced with the random generator buttons. (Patron button was always there)
I'll toss some code to disable the patron button on mobile.

This is dmv specific so their won't be a pull for this fix.

**Comment by datdamnzotz** [comment]
Tad better.  Could use some more work on the right but a good hot fix...
![image](https://user-images.githubusercontent.com/3913859/87099157-49aeb480-c206-11ea-9ff6-492f2f35a075.png)

**Comment by Pireax** [comment]
Thanks for looking into this, I see it shows the other social network links now, it didn't before, was that intended? I think without that it'll fit almost perfectly.

**Comment by datdamnzotz** [comment]
yah I tossed them back in there : ]

**Comment by Pireax** [comment]
I saw this was changed on the live site already, nice things get handled so quickly but it hasn't really solved the issue :(.

This is how it looks now on my phone: 
![image](https://user-images.githubusercontent.com/11289656/87234647-592f2880-c3d3-11ea-8c12-fee1bba9cefa.png)

**Comment by codeGlaze** [comment]
I'm screwing with the css.
Mostly likely going to redo the social bar.
