### ISSUE TITLE
Make all expandable items clickable anywhere

### ISSUE THREAD

**Issue by Pireax** [Orcpub/orcpub#414]
**Motivation / Use Case**
There is different behaviour for different expandable items in the user interface, some, such as spell slots expand when clicked on anywhere (screenshot 1), while other items such as in screenshot 2 require you to click the up / down arrow (which is a drag on mobile). Also the expansion arrows are touching the edge of the items in screenshot 2.

**Expected Behavior**
Clicking an expandable item anywhere (except on buttons etc in the item) expands the item.

**Screenshots**
1. ![image](https://user-images.githubusercontent.com/11289656/87091348-cb6c0580-c239-11ea-9c3d-17032406ae9c.png)
2. ![image](https://user-images.githubusercontent.com/11289656/87091289-b7280880-c239-11ea-904d-d18743b76651.png)

**Comment by datdamnzotz** [comment]
This probably could be possible, but the Roll button is what removed that functionality.  (Can't roll and expand at the same time... well probably could, but that would be weird.

**Comment by Pireax** [comment]
Yeah I get what you mean, what I think would make sense is that clicking anywhere on the item will expand it except when clicking on the roll / other buttons, when clicking on the roll button it should not expand but just do the 'roll' action.
