### ISSUE TITLE
Page height on mobile is too small when address bar is not visible

### ISSUE THREAD

**Issue by Pireax** [Orcpub/orcpub#415]
**Describe the bug**
When scrolling down on the page the address bar in chrome slowly starts to disappear and the page becomes larger, the content height does not update (html, body tag heights stay the same) and this causes a white area to appear at the bottom with the size of the address bar.

**To Reproduce**
1. Go to any page
2. Scroll down a bit to make the browser address bar disappear

**Expected behavior**
Page resizes to fit new viewport size

**Screenshots**
![image](https://user-images.githubusercontent.com/11289656/87097247-07589800-c245-11ea-8ac7-d315d116ce0b.png)

**Smartphone (please complete the following information):**

 - Device: Xiaomi Mi 9T
 - OS: Android 10
 - Browser: Chrome
 - Version: 83

**Additional context**
Related post: https://developers.google.com/web/updates/2016/12/url-bar-resizing
Adding `position: fixed` to the html tag somewhat fixes the issue but it's not very responsive, it still takes a while for the page to update the height.

**Comment by datdamnzotz** [comment]
This is going to be a hard one for me to fix... I don't have an droid to test on.

**Comment by Pireax** [comment]
I think this is chrome specific, does iOS not also have chrome? Anyhow the `position: fixed` seems like a quick fix but I don't know how that will affect other browsers (i.e. safari, etc.)

**Comment by codeGlaze** [comment]
We may just need to change to flex.

Edit: Firefox does it too

**Comment by datdamnzotz** [comment]
Works fine on IOS with chrome.
