### ISSUE TITLE
Account menu does not work on mobile

### ISSUE THREAD

**Issue by Pireax** [Orcpub/orcpub#416]
**Describe the bug**
The account menu in the top right corner of the header only opens on hover and not when clicked on, this makes it unusable on a tablet / phone.

**To Reproduce**
1. Login
2. Go to any page
3. Click on the account menu

**Expected behavior**
The account menu pops up with the items `logout` and `account`.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T
 - OS: Android 10
 - Browser: Chrome
 - Version: 83

**Additional context**
The main menu buttons (characters, spells, etc..) work as expected.

**Comment by datdamnzotz** [comment]
IOS w/Chrome works.   Again going to be hard to troubleshoot since I don't have one.
![image](https://user-images.githubusercontent.com/3913859/87101758-25a2a180-c20d-11ea-9cb2-1a5b565860df.png)

**Comment by codeGlaze** [comment]
Can confirm.
Android with Brave.

**Comment by datdamnzotz** [comment]
> Can confirm.
> Android with Brave.

Confirm it works? or doesn't....

**Comment by codeGlaze** [comment]
Having difficulty pinpointing what's causing this not to work :/
