### ISSUE TITLE
Blank Spell entry bug

### ISSUE THREAD

**Issue by Frost2779** [Orcpub/orcpub#42]
I have found out a bug when it comes to empty spell entries (shown below). Additionally I was able to I believe track down where the issue is coming from. Take Booming Blade for example. In one of my commits that got merged I commented the spell out in the 'cljc/orpub/dnd/e5/spells' file, but not in the 'spell_lists' where the spells that each class has to choose from are. I believe what is happening here is that since I commented it out in one place but not the other it is trying to look for the spell but is simply getting some type of error or empty response, and is in turn replacing it with a blank spell box. 

A question I has was how should I handle solving this. Should I restore all commented out spells in the 'spells' file, so that the only place we need to worry about removing anything spell related, due to SRD or what have you, is in the 'spell_lists' file? So for example I would restore Booming Blade in the 'spells' file, but then comment out all occurrences of it in 'spell_lists'.

![bug](https://user-images.githubusercontent.com/11138682/51431376-74114a00-1bed-11e9-8cbb-1d1cf269a2d0.png)

**Comment by Demonsthere** [comment]
IMHO we need to remove all non SRD content from the code to avoid any legal issues

**Comment by datdamnzotz** [comment]
for the repo just needs to have SRD.

**Comment by MeanderingCode** [comment]
I agree that we can simply remove the entries from both places, instead of commenting them out.

Could you do this in your PR #44, @Frost2779 ?

**Comment by Frost2779** [comment]
I sure can.

**Comment by Demonsthere** [comment]
As #44 is merged, I will close this now
