### ISSUE TITLE
Compact proficiency indicator

### ISSUE THREAD

**Issue by Pireax** [Orcpub/orcpub#428]
Currently we show for proficiencies for weapons, armor and the proficiencies table like

![image](https://user-images.githubusercontent.com/3913859/87879544-b5341700-c9a8-11ea-905a-16649745baaa.png)

**Proposed Change/ Motivation / Use Case**
Currently the proficiency is indicated by a check mark in a separate column taking up a lot of space for little (but important) information. I think most people are familiar with the radio buttons that show proficiency on a 5e character sheet so I would suggest using these (with a tooltip) to indicate the proficiency instead of a separate column like so:

Unproficient:
![image](https://user-images.githubusercontent.com/11289656/87855792-dd753480-c91a-11ea-9199-05ad028ee950.png)
Proficient:
![image](https://user-images.githubusercontent.com/11289656/87855812-0a294c00-c91b-11ea-8ead-41d80924eb3e.png)

Edit DatDamnZotz - add current state.

**Comment by codeGlaze** [comment]
Why not just move the x or check to the spot you placed the radio?

**Comment by Pireax** [comment]
The check itself does not convey any meaning as to what the check is for (it's too generic), it would still need a header like `Proficiency` (which is taking up the most space). The icons used here convey the semantics without needing a header.

**Comment by codeGlaze** [comment]
Ah. I disagree.

New people would have no idea.
We have seen many different cross-sections of the community. If something has a label... it's probably best to keep it in some capacity.

Could theoretically add it to the style chooser 🤔

Either that or shorten the column header `Prf?`, `Prfc?`, `Prof?`

**Comment by DivertedCircle** [comment]
I would argue that neither option is ideal, and that whether you're proficient or not should be the first thing listed in the Details section.

**Comment by codeGlaze** [comment]
Just a thought, this is something that could mocked up in a spreadsheet for those who would like to posit changes.

**Comment by Pireax** [comment]
I'm not sure what you mean by that @codeGlaze, could you expand on that?

> New people would have no idea.
We have seen many different cross-sections of the community. If something has a label... it's probably best to keep it in some capacity.

Does the tooltip not take care of this?

EDIT: By the way, proficiency is also already indicated in the summary by means of the brightness of the skills / ability scores, we could also use this method. Anyhow, I would argue that it's nice to have it be consistent. 
![image](https://user-images.githubusercontent.com/11289656/87874015-8e84d900-c9c6-11ea-9816-920cbaf75349.png)

**Comment by datdamnzotz** [comment]
I think it s a good idea since we are not showing that today on weapons (I think there is a backlog issue some place?)
Might want a legend to show what it means, just so people know.
Tool tips are ok on Desktop side but on the mobile side I haven't seen them pop up.

**Comment by codeGlaze** [comment]
Mobile tooltips normally show on long press.

🤔 ...or is that alt-text?

**Comment by datdamnzotz** [comment]
> Mobile tooltips normally show on long press.
> 
> 🤔 ...or is that alt-text?

And who *EVER* long presses on stuff LOL I don't.

**Comment by datdamnzotz** [comment]
Added Patron poll for this one as well.  Open for 7 days.

**Comment by codeGlaze** [comment]
> > Mobile tooltips normally show on long press.
> > 🤔 ...or is that alt-text?
> 
> And who _EVER_ long presses on stuff LOL I don't.

🤣 Well... not too many options for interacting with stuff on mobile otherwise!

**Comment by datdamnzotz** [comment]
I think the question is how we do it so it is most clear : ]
Gotta think of the newbies and the seasoned vets. and getting it to work on mobile as well - and color challenged people.

**Comment by Pireax** [comment]
Since weapon proficiency in dnd 5e is very simple and each weapon is either `simple` or `martial` maybe the best solution is simply to state the weapon type in the details summary column and remove the proficiency column altogether, this allows you still to see if you're proficient at a glance, is hard to wrongly interpret. Also since the attack bonus already takes proficiency into account it's not something you actually need as often. This would look something like this:
![image](https://user-images.githubusercontent.com/11289656/87882515-a4af8b00-ca00-11ea-8ed0-a1c24ba2c792.png)

Or something like this with alternative roll buttons:
![image](https://user-images.githubusercontent.com/11289656/87882647-c2312480-ca01-11ea-8a19-7f4ca8c16934.png)

Instead of displaying `simple` or `martial` we could also display `proficient` in the details as @codeGlaze has suggested.

**Comment by Butterfly-Dragon** [comment]
also: make that proficiency a checkbix for the items created by the users! so that people can decide by themselves if their character knows or not how to use the claws they were born with. 😂👍💖

**Comment by Arkonos** [comment]
> Since weapon proficiency in dnd 5e is very simple and each weapon is either `simple` or `martial` maybe the best solution is simply to state the weapon type in the details summary column and remove the proficiency column altogether, this allows you still to see if you're proficient at a glance, is hard to wrongly interpret.

That alone isn't sufficient as a sorcerer starts with select proficiencies like daggers and darts, but not the whole simple category.
Likewise, a rogue has simple and in addition select martial weapons.
Adding it as a keyword would solve this, but would also introduce character based information to the weapon details.
 
A radial button would make sense if one can toggle the state directly from the menu, but I'm not sure if that'd be good thing.

Displaying the affected modifier in red or similar colour for lacking proficiency would suffice. If I need to check which proficiencies I have I can check the proficiencies tab. In my admittedly limited experience I've very rarely seen a character use equipment he's not proficient with.

**Comment by codeGlaze** [comment]
>In my admittedly limited experience I've very rarely seen a character use equipment he's not proficient with.

New players do crazy things.
And we need to keep in mind that these tools are for new and experienced. So clearness is important.

Concatenating the prof/expertise in to the description shouldn't be overly complex.

What about letters instead of radials?
So ... nothing for NP, a **P** for Proficient and and **E** for expertise where applicable?

**Comment by Butterfly-Dragon** [comment]
It is already possible to write down which kind of weapon a weapon is (simple, martial, etc.) as well as connecting it to an existing weapon and use that proficiency.

The system blatantly disregards such "claims" and locks every single weapon as "non proficient" regardless of any choice made.

While that is indeed a bug (and a known one, since i opened the ticket ages ago) if you guys add a check mark for the proficiency, it adds readability, and making it a checkbox, but only for custom items, (rather than a radial, which once selected, by mistake,  cannot be "unselected") also solves this problem.

**Comment by codeGlaze** [comment]
@Butterfly-Dragon
While it's a good idea, it's a separate topic. ;)

*That being said* tying it to the homebrew brew-mug might be a good way to implement that functionality.

**Comment by barefootcoder** [comment]
My vote would be one of the following:
* Move the check mark (or radio button or what-have-you) to the left of the name, as in the top post, but retain a column header—just make it shorter.  "Prof?" is plenty sufficient; also, make the font for that one header smaller so it takes up less space.  Use a tooltip for explaining what "prof" means for the truly uninitiated, although I think most will get it.
* Forget having any symbol at all: just use colors.  Make all proficient skills (and weapons) green or somesuch.  Add a line of (same color) text at the top as a legend, e.g. "Proficient skills listed in green."

Either of those should conserve screen real estate and still seem pretty clear to me.

**Comment by datdamnzotz** [comment]
Poll results
![image](https://user-images.githubusercontent.com/3913859/88717495-dd74f180-d0dd-11ea-8e49-3f29c3345400.png)

**Comment by Pireax** [comment]
A lot of differing opinions on this, maybe let's wait a bit with this one until a later release.

**Comment by datdamnzotz** [comment]
> A lot of differing opinions on this, maybe let's wait a bit with this one until a later release.

Or come up with a A/B/C... comparison and let ppl vote.

**Comment by datdamnzotz** [comment]
Resolved via #436
