### ISSUE TITLE
Mobile roll buttons bleed off the screen

### ISSUE THREAD

**Issue by datdamnzotz** [Orcpub/orcpub#429]
**Describe the bug**

![shot](https://user-images.githubusercontent.com/3913859/87869010-251ab100-c959-11ea-9032-45843af83e32.jpg)

**To Reproduce**

1. Go to a weapon and expand it's details

**Expected behavior**

Shouldn't do this,.

Browser :safari, :browser-version "13.1.1"
Device-type :mobile, 
Platform :ios, :platform-version "13.5.1"

**Comment by Pireax** [comment]
One of #427 or #428 would likely already solve this as it would leave more space for the details row, but if neither gets accepted we could move the details to align with the first column (like spells)?

**Comment by datdamnzotz** [comment]
Resolved via #427
