### ISSUE TITLE
Missing versatile damage button - items with versatile damage don't have a button

### ISSUE THREAD

**Issue by CatgirlChilis** [Orcpub/orcpub#455]
**Describe the bug**
While making a character recently, I discovered an inconsistency between warhammers on the DMV and in every other official and non-official source i've looked at
According to non-DMV sources, warhammers have the versatile property, dealing 1d8 damage when used one handed, and 1d10 when used two-handed
the DMV character sheet treats warhammers as a two-handed only weapon that deals 1d8 damage only

**To Reproduce**

1. Make a character with a warhammer
2. equip it, and no other offhand weapons or shields
3. The damage is still listed as 1d8 and there is no option to equip an offhand weapon

**Expected behavior**

DMV should allow a second light weapon to be equipped with the warhammer, the warhammers damage should be 1d10 when no other weapons or shields are equiped

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Opera
 - Version: 2.5.0.17

**Comment by DivertedCircle** [comment]
Warhammer's are not light weapons, which is why you are not getting the option to equip a second one. Also, the 1d10 property is displaying fine, as shown in the screenshot.
![image](https://user-images.githubusercontent.com/26470570/94355927-dae33980-0045-11eb-898e-dc883711d15c.png)

**Comment by CatgirlChilis** [comment]
Oh sorry, I missed that. in that case the only problem is that the damage still doesn't update in the "attacks" list, despite it being the only weapon or shield equiped, unless I missed something here too
![image](https://user-images.githubusercontent.com/17153074/94489647-15fa7f80-01a2-11eb-9aea-91ad9ea64ff3.png)

**Comment by datdamnzotz** [comment]
Correct, the site doesn't show Versatile damage currently - just the normal damage.
![image](https://user-images.githubusercontent.com/3913859/94655344-a973a380-02bb-11eb-8c43-5048c43fcee1.png)
