### ISSUE TITLE
Subrace - spell-like ability not unlocking as entered

### ISSUE THREAD

**Issue by Midknyghte** [Orcpub/orcpub#463]
**Describe the bug**
For the subrace I added to the character creator, Earth Genasi as per the rules on http://dnd5e.wikidot.com/genasi.

At level 1, the character should have access to a spell-like ability of Pass Without Trace, one time per long rest. As the spell Pass Without Trace is a 2nd level spell, it will not unlock for the character at level One as it is entered.

**To Reproduce**

1. Go to the subrace builder
2. Click on Spells
3. Scroll down to -
     Unlock at Level: 1
     Spell Level: 2
     Spellcasting Ability: Constitution
     Spell: Pass Without Trace
4. See error: Spell ability does not unlock at level 1

**Expected behavior**

At level One the spell should be available one time per long rest.

**Screenshots**

![Desktop Screenshot 2020 10 12 - 15 27 19 08](https://user-images.githubusercontent.com/68384259/95713667-e9665d80-0ca1-11eb-81c4-3c305246c04c.png)
![Desktop Screenshot 2020 10 12 - 15 27 41 08](https://user-images.githubusercontent.com/68384259/95713672-ea978a80-0ca1-11eb-8fa0-aa61568b823b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DivertedCircle** [comment]
The spell is unlocking fine, as shown in your screenshots. It's not giving an option to cast it with spell slots because you don't have the appropriate level slot, but you don't need a slot to cast it because it's an innate ability.
