### ISSUE TITLE
Saving Throws for Ability

### ISSUE THREAD

**Issue by VinceYotaz** [Orcpub/orcpub#469]
Hello,

this character:
https://www.dungeonmastersvault.com/pages/dnd/5e/characters/17592240294761

i don't understand why my Saving Throws for Abilities are so high.

normally, for a Paladin, the proficiencies are on Charisma and Wisdom and they seem to be right. 

but, from strenght, + 8 should be +6 no?
Dex + 4 should be +1
Con + 6 sould be + 3
Int + 3 should be 0

It's like I have a permanent + 3 but I don't understand why.

thanks for your help

**Comment by averycrespi** [comment]
> Features, Traits, and Feats
> Aura of Protection
> You and friendly creatures within 10 ft. have a +3 bonus to saves.

I think that's why.

**Comment by VinceYotaz** [comment]
ahhhhh...many thanks!!!!
