### ISSUE TITLE
Variant character sheet - The font sizes very small for skills and saving throws

### ISSUE THREAD

**Issue by datdamnzotz** [Orcpub/orcpub#479]
**Describe the bug**
The font sizes very small for skills and saving throws and difficult to read.

**Screenshots**
Acrobat: 
![image](https://user-images.githubusercontent.com/3913859/99423563-e91f3a80-28bd-11eb-8c13-9082363a766e.png)

Chrome
![image](https://user-images.githubusercontent.com/3913859/99423672-06540900-28be-11eb-8b98-ea8bcc29ecd5.png)

**Desktop (please complete the following information):**

-Chrome or Adobe Acrobat

**Comment by Jessomadic** [comment]
This is because the sheets font sizes are set to auto and the field is prob not big enough. I can fix it if you like
