### ISSUE TITLE
Clean up the My Content list and other buttons

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#49]
**Is your feature request related to a problem? Please describe.**
The My Content list doesn't seem to follow any specific order and much of it is building tools that don't really belong there.

**Describe the solution you'd like**
- Rename the Builder and Parties links in the Characters button to Character Builder and Party Builder.
- Remove the link to the Spell Builder as it already exists when hovering over the Spells button.
- Remove the link to the Monster Builder as it already exists when hovering over the Monsters button.
- Move the Encounter Build and the Combat Tracker to a new button labelled Encounters.
- Move all other builder links from the My Content button to the Characters button.

**Comment by datdamnzotz** [comment]
Fixed by #85
