### ISSUE TITLE
[Feature Request] Add schedule 4 for spell casters

### ISSUE THREAD

**Issue by datdamnzotz** [Orcpub/orcpub#494]
**Motivation / Use Case**
Add spell slot schedule 4 to 
https://github.com/Orcpub/orcpub/blob/develop/src/cljc/orcpub/dnd/e5/options.cljc

4 {1 {1 2}
       3 {1 1}
       5 {1 1
          2 2}
       7 {2 1}
       9 {3 2}
       11 {3 1}
       13 {4 1}
       15 {4 1}
       17 {4 1
           5 1}
       19 {5 1}}

**Comment by DivertedCircle** [comment]
Add spell slot schedule 5 to
https://github.com/Orcpub/orcpub/blob/develop/src/cljc/orcpub/dnd/e5/options.cljc

5  {1 {1 1}
     2 {1 2}
     3 {2 2}
     4 {2 2}
     5 {3 2}
     6 {3 2}
     7 {4 2}
     8 {4 2}
     9 {5 2}
     10 {5 2}
     11 {5 3}
     12 {5 3}
     13 {5 3}
     14 {5 3}
     15 {5 3}
     16 {5 3}
     17 {5 4}
     18 {5 4}
     19 {5 4}
     20 {5 4}})

Add spell slot schedule 6 to
https://github.com/Orcpub/orcpub/blob/develop/src/cljc/orcpub/dnd/e5/options.cljc

6  {3 {1 1}
     4 {1 2}
     5 {2 2}
     6 {2 2}
     7 {3 2}
     8 {3 2}
     9 {4 2}
     10 {4 2}
     11 {5 2}
     12 {5 2}
     13 {5 3}
     14 {5 3}
     15 {5 3}
     16 {5 3}
     17 {5 3}
     18 {5 3}
     19 {5 4}
     20 {5 4}})
