### ISSUE TITLE
[Bug]Login request upon saving characters

### ISSUE THREAD

**Issue by ChxssMix** [Orcpub/orcpub#496]
**Describe the bug**
Every time I go to save my character on mobile it will ask me to login even though I have time and time again. 

**To Reproduce**

1. Go to character builder
2. Click on the save file
3. Then login as it asks
4. See that it doesn't save

**Expected behavior**

I expected it to save my character profile and not login over and over and not save. 

**Screenshots**

**Smartphone (please complete the following information):**

 - Device: Samsung Galaxy A20
 - OS: Verizon
 - Browser: Google chrome
 - Version: Newest upon as of Dec 17 2020

**Comment by datdamnzotz** [comment]
Hey @ChxssMix is this a character you have under your account or is it one someone sent you?
You can only edit the characters you account owns.

**Comment by ChxssMix** [comment]
It is a character I was creating. I am able to save it if I make a copy of
the profile and then save it. But it's strange because it doesn't happen
often. I hope this problem gets resolved because I love using the site and
being able to use it on mobile is useful because I don't always have access
to my laptop. Thank you for responding so quickly and thank you for your
time.

**Comment by datdamnzotz** [comment]
Are you running Google chrome in incognito?

**Comment by datdamnzotz** [comment]
Unable to reproduce.
