### ISSUE TITLE
[BUG] Multiple Shifter subraces being selected

### ISSUE THREAD

**Issue by WoernerBro** [Orcpub/orcpub#498]
**Describe the bug**

For the Shifter race, when selecting any of the multiple copies of Beasthide, Longtooth, Swiftstride, or Wildhunt will select all copies of that subrace. This causes only the bottom version of the duplicates to be active.

**To Reproduce**

Select Shifter as your race and select Beasthide, Longtooth, Swiftstride, or Wildhunt as your subrace.

Example: Beasthide

![image](https://user-images.githubusercontent.com/21225335/103161646-7ce00280-47aa-11eb-80de-2d801015b81a.png)

**Comment by codeGlaze** [comment]
That's non-SRD content, so not something we have control over.

If you or a friend made that for your own use I would change the names. Each Shifter should be something like "Shifter (description)" to say how it's different.

Those names get turned into a key that's used by the logic behind the scenes. So you or the content creator made three identical shifter keys. Adding a small descriptor should fix it.

**Comment by WoernerBro** [comment]
Got it. Sorry for the bother
