### ISSUE TITLE
Invalid .orcbrew file

### ISSUE THREAD

**Issue by trogdor7** [Orcpub/orcpub#502]
**Describe the bug**
I added a new custom "subclass" for a Barbarian as a primal path unlocked at level 3. I saved the new subclass after adding in all features to my local browser storage, and then clicked the link to download the .orcbrew file as the site prompted me to. When I go to upload that file that I just downloaded back into dungeonmastersvault, it tells me that the .orcbrew file is invalid.

**To Reproduce**

1. add a new subclass
2. save locally to browser storage
3. download .orcbrew file
4. try to upload .orcbrew file just downloaded into custom content
5. See error

**Expected behavior**

I should be able to upload the .orcbrew file that was just downloaded from the dungeonmastersvault site back to the site so I don't lose my custom content and have to add new content every time my browser cache is cleared.

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Chrome
 - Version 87.0.4280.141

**Comment by DivertedCircle** [comment]
From the discord server:
![image](https://user-images.githubusercontent.com/26470570/104777059-49a0eb80-5738-11eb-93bf-ab2765980d96.png)

**Comment by trogdor7** [comment]
Is there a way to make make the file work or are there plans to fix this issue on the website? I've tried twice to export the .orcbrew file both times creating the same custom content from scratch. Both times it said that it was an invalid file when I tested it by trying to upload.

**Comment by DivertedCircle** [comment]
It's a known issue but if we knew how to fix it we would have done so already. You can upload your content file to the Discord (if it doesn't contain duplicates of copyrighted content) and someone there may be able to fix it. The only other option is to export the file multiple times until you get one that works, or create all the content over again from scratch

**Comment by datdamnzotz** [comment]
No example - unable to reproduce.
