### ISSUE TITLE
Issue With DMV Account

### ISSUE THREAD

**Issue by MintMagician** [Orcpub/orcpub#527]
Hey there,

I have never really used GitHub in this way before, so I apologize if this is not the proper format for a bug report or complaint.

I tried logging into my DMV account today to finish working on some character sheets and received a notification I've never seen before; DMV was telling me that my email address was not associated with any registered account on the site. I thought maybe I was doing something wrong or that perhaps I was receiving the message in error and had simply forgotten my password but that, as best as I can tell, does not seem to be the case. I like and use this site enough that I support it on Patreon. My account was previously registered through Patreon to make use of the experimental features and the bonus character sheets. I don't know what I could have done on my end between now and the last time I used the service to have terminated my own account and I'm not really sure who to contact about this.

I've attached some photos showing the issues I've been having, along with some proof of my Patreon support and hopefully some additional evidence that as of yesterday, I definitely had an account registered to my grizzlemeat@gmail.com email.

Thank you for taking the time to read this,

Mint

![Capture](https://user-images.githubusercontent.com/81826777/113443700-1b868b80-93b8-11eb-98b9-b1d6a647681d.PNG)

![Capture2](https://user-images.githubusercontent.com/81826777/113443717-23463000-93b8-11eb-9002-8e1aad91c468.PNG)

![Capture3](https://user-images.githubusercontent.com/81826777/113443730-293c1100-93b8-11eb-9211-58cfa666c334.PNG)

**Comment by datdamnzotz** [comment]
Hey Mint - I'll contact you via email and close this issue.
Github is really for feature requests and bugs. 

Account fixes etc I can take care of through email at thDM@dungeonmastersvault.com - also if you want you can join the discord server as well.
