### ISSUE TITLE
[BUG] Saving a character redirecting me to login when already logged in

### ISSUE THREAD

**Issue by UristMcArmok** [Orcpub/orcpub#529]
Im not sure whats causing this, but on occasion trying to save a character redirects me to login. Reloading, closing and opening new tab, etc dont seem to help. Sometimes it fixes itself but im not sure how to do it intentionally.

**Comment by codeGlaze** [comment]
Try logging in with an incognito window. No custom content loaded.

**Comment by datdamnzotz** [comment]
Currently you can not edit characters from other accounts because you are not an owner of that character. You can only edit characters that are under your logged into account.  You will be redirected to sign in if you don't own the character.
