### ISSUE TITLE
My Content Folders

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#53]
**Is your feature request related to a problem? Please describe.**
The My Content page does not allow sorting, instead displaying all content seemingly at random. Adding folders and allowing sorting will make for a shorter list.

**Describe the solution you'd like**
Allow custom sorting including folder functionality. Even just alphabetically sorting would be an improvement.

**Comment by johnliss** [comment]
Like this?
![image](https://user-images.githubusercontent.com/3913859/51815877-1c27b280-2281-11e9-88ff-38f32b462463.png)
