### ISSUE TITLE
Different content with same account on different computers

### ISSUE THREAD

**Issue by scott-e-stanford** [Orcpub/orcpub#530]
**Describe the bug**
When I log into my account and begin editing a character, the available content depends on which computer I am using. On my two MacBooks, I have expanded content from the Player's Handbook, Xanathar's Guide, etc. But when I log into the same account on my Windows machine, I only see SRD content.

**To Reproduce**

1. Log into DMV.
2. Edit a character.

**Expected behavior**
Content based on my account; not on what computer or browser.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: Different between Windows and MacOS
 - Browser: Chrome
 - Version: Latest
<img width="878" alt="DM Vault on Windows" src="https://user-images.githubusercontent.com/83807978/117413193-86047d00-aeca-11eb-9c6e-b8de24416a88.png">
<img width="496" alt="DM Vault on MacOS" src="https://user-images.githubusercontent.com/83807978/117413260-99afe380-aeca-11eb-81d1-cc2b6bf9ab85.png">

**Comment by DivertedCircle** [comment]
This is not a bug. Orcbrew content is saved to your browser cache, not your account. There has been discussion about a cloud based storage system instead but nothing has been solidified.

**Comment by scott-e-stanford** [comment]
OK, I was wondering if it was something like that (not fully understanding
how that works). Is there a document that describes how I can upload /
share my browser cache across different devices?

**Comment by DivertedCircle** [comment]
https://www.dungeonmastersvault.com/help/known-issues-site-limitations/

**Comment by scott-e-stanford** [comment]
I guess the pertinent article is
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria
, and perhaps this
<https://developer.chrome.com/docs/devtools/storage/localstorage/>one
<https://developer.chrome.com/docs/devtools/storage/localstorage/> for
Chrome. (I'm not a developer by any means, so hoping this isn't too hard
for a layperson!)

**Comment by DivertedCircle** [comment]
No, that's not it.

![image](https://user-images.githubusercontent.com/26470570/117487982-0c4fac00-af29-11eb-8794-5ab1bfe72679.png)
![image](https://user-images.githubusercontent.com/26470570/117488033-1d98b880-af29-11eb-8358-cfe124031703.png)

Export the content you set up on one computer in the My Content tab, send it to the other computer, and upload it in the My Content tab.

**Comment by codeGlaze** [comment]
You can export your content and save it to a cloud drive (gdrive, Dropbox, etc). Then justice there drive to upload your content when you need it.

Should work for just about every platform
