### ISSUE TITLE
Mobile: Screen goes blank when selecting classes tab

### ISSUE THREAD

**Issue by nSword0** [Orcpub/orcpub#535]
**Describe the bug**
As the title states, when you tap on the classes tab, the entire screen goes blank, all that being left is what I assume is the background image of the page. This happens either tapping directly on the tab or using the next/previous buttons.

[A video of it happening](https://gfycat.com/immensewiltedalbertosaurus) 

 - Device: Google Pixel 5
 - OS: Android 11
 - Browser: Google Chrome
 - Version 91.0.4472.88

**Comment by codeGlaze** [comment]
That typically means you have corrupt data. It can happen for a few reasons but normally it has to do with your custom content.

Log in via an incognito window and load only the sources you absolutely need for the character to function. See if they helps.

**Comment by nSword0** [comment]
> That typically means you have corrupt data. It can happen for a few reasons but normally it has to do with your custom content.
> 
> Log in via an incognito window and load only the sources you absolutely need for the character to function. See if they helps.

Did this, and sure enough it worked. Then on a hunch I exported my custom content from my normal window and exported it in the incognito window, but it continued to work fine. I just deleted all my custom content then re-imported it and it seems to have been resolved.
