### ISSUE TITLE
Various Changes To PDF Sheets

### ISSUE THREAD

**Issue by Jessomadic** [Orcpub/orcpub#536]
**Describe the bug**
Many Areas across all the pdfs are not displaying size correctly.

**To Reproduce**
Generate a PDF

**Expected behavior**

All text fit correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/35648348/125171577-fb1e5800-e182-11eb-98db-a2a76a45050b.png)
****

**Comment by codeGlaze** [comment]
So you fixed it to auto-resize as per the screenshot?

**Comment by Jessomadic** [comment]
Indeed it has been fixed 
![image](https://user-images.githubusercontent.com/35648348/129419760-5645d3da-6555-4cbe-97e4-d9353d9598c4.png)

**Comment by codeGlaze** [comment]
I feel like a derp, misread this and thought it was a push not a close.

**Comment by Jessomadic** [comment]
All good it happens

**Comment by datdamnzotz** [comment]
It will autoclose when the pull request gets merged.
