### ISSUE TITLE
Custom Warlock Patron

### ISSUE THREAD

**Issue by ashf** [Orcpub/orcpub#54]
**Describe the bug**
Warlock Otherworldy Patrons are utilized via subclass. When creating a new one, you must specify a skill proficiency and expertise choice, even if not granted by that Patron. Even if nothing is selected, in the "Proficiencies" tab a Warlock Skill Proficiency - Otherworldy Patron must be chosen.

**To Reproduce**
1. Select Warlock Class
2. Add subclass
3. Don't select proficiency/expertise choice.
4. Go to Proficiencies tab
5. Warlock Skill Proficiency - Otherworldy Patron is still required

**Expected behavior**
No Warlock Skill Proficiency - Otherworldy Patron is required or displayed as an option

**Screenshots**
![image](https://user-images.githubusercontent.com/6597733/51546907-300f8680-1e33-11e9-8f69-4e81e27da03f.png)
![image](https://user-images.githubusercontent.com/6597733/51546962-474e7400-1e33-11e9-8c8d-50fa177a70c2.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 71.0.3578.98

**Comment by DivertedCircle** [comment]
From the looks of it those three proficiencies were selected at some point when making the subclass. If that's happened then sometimes even though you uncheck them they still appear. Can you share the orcbrew file?

**Comment by ashf** [comment]
you're not wrong, I made a new subclass and never checked anything. The Warlock Skill Proficiency - Otherworldy Patron is no longer an option on the Proficiencies tab.

So... I guess the bug is that the orcbrew file doesn't clean itself up (if that makes sense?).

**Comment by ashf** [comment]
To note further... I opened the orcbrew file and removed the prof info for that subclass. Issue resolved. I will close this bug and open a new one about the orcbrew file not cleaning itself up.
