### ISSUE TITLE
Spellcasting to subclasses

### ISSUE THREAD

**Issue by Aleks-1995** [Orcpub/orcpub#540]
I cant seem to find the option to add spellcasting to a subclass similar to eldrtich knight. Im trying to do the elemental practice of rain junkies dragon knight. Anyone got an idea how to do it?

TY

**Comment by DivertedCircle** [comment]
It's not currently possible to do so for any class from the PHB that doesn't have a subclass that gains spellcasting. This means only Fighters and Rogues can have subclasses that gain spellcasting, and they're limited to wizard spells. The only work around at the moment is to build the entire class as a standalone, and include the subclass features as part of the class.

**Comment by Aleks-1995** [comment]
Okay good to know. Thanks a lot
