### ISSUE TITLE
Warlock: Great Old One spells.

### ISSUE THREAD

**Issue by Midknyghte** [Orcpub/orcpub#545]
Today I went in to make a Warlock with a subclass of Great Old One. Of course there is not one. Not a big deal, I have made subclasses before. 

The problem is that the spells I need to add to the spell list are not available as options.

I.E.
1st dissonant whispers, Tasha's hideous laughter
2nd phantasmal force
3rd sending
4th Evard’s black tentacles

**Comment by Jessomadic** [comment]
The site can only use SRD content legally so we can not add it. No named spells are allowed under that ruleset but the spell still exists on the site just under Hideous Laughter and its the same for most of the caster named spells.
![image](https://user-images.githubusercontent.com/35648348/141936139-2a13b7e1-2c7d-49b5-90e1-d227bba39587.png)

**Comment by Midknyghte** [comment]
OK. So I have Black Tentacles and Hideous Laughter.  Turns out I missed Sending, it is there.

That still leaves me short on spells: 1st Dissonant Whispers and 2nd Phantasmal Force.

**Comment by Jessomadic** [comment]
Those two spells are not part of the SRD that Wizards allows us to use. The document is here 
https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf
There is a spell builder on the site however where you can build your own spells but we can not provide them and of course, support Wizard's Of The Coast and only use the content you own.

**Comment by Midknyghte** [comment]
OK, I wasn't aware of that.  Thanks.
