### ISSUE TITLE
Browser Refresh Required

### ISSUE THREAD

**Issue by Brugga** [Orcpub/orcpub#557]
**Describe the bug**
I've recently returned to DM'ing and used Dungeon Master's Vault to manage characters in the past.  I came back here and found past NPCs and such just as I'd left them.  What I began to notice, however, is a need to hit refresh in my browser when making some selections.  This appears to happen if I'm using Chrome or Edge, and on both my Windows laptop and Windows desktop.  If I'm just viewing content already entered it's not an issue.  If I try to make edits, however, it's a problem as refreshing can end up taking you to a blank form rather than the content you want to update.

**To Reproduce**

1. Go to My Content.
2. Click on Content List.  At this point I get a blank browser window and must refresh.
3. Scroll down any custom content previously entered select "Edit".  At this point I get another blank browser window and must refresh.
4. The refresh does not display the custom content I wanted to update, rather it gives me the builder form where I could enter new custom content.  The error being, I am unable to edit and make updates to custom content previously entered.

**Expected behavior**

I do not expect to need to hit refresh in order to see content after making selections.

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: Microsoft Windows 11 and 7
 - Browser: Chrome and Edge

**Comment by DivertedCircle** [comment]
Try disabling any adblock software you're using and try again. Also try in an incognito window.

**Comment by Brugga** [comment]
I excluded www.dungeonmastersvault.com from my adblocker and continued to experience the issue.  Using an incognito window did not require browser refreshes, however.  Knowing this, is my solution to always use an incognito window for https://www.dungeonmastersvault.com or does this help to identify some other fix that would return things to the way the website was for me previously?

**Comment by datdamnzotz** [comment]
Turn off your Ad Blocker
If you hit F12 and check the Browser Console and see this:

![image](https://user-images.githubusercontent.com/3913859/154848096-7d7aea6e-da2e-4aa4-8feb-46c4dc4d51d3.png)

It’s adblockers.

* Turn off your adblockers, CNTRL+F5 refresh
* Open in an incognito mode with no homebrew loaded, CNTRL+F5 refresh
* Only load the homebrew needed for your current character, CNTRL+F5 refresh
