### ISSUE TITLE
Blank Box Proficiencies Tab

### ISSUE THREAD

**Issue by NebulasNova** [Orcpub/orcpub#558]
A blank box in the weapons proficiencies section, when clicked it is undetectable and when clicked again adds more and more "need to be removed" proficiencies. The issue requires a refresh of the character builder to fix but the box is still there.

1. Go to The weapons section in the proficiencies tab
2. Click on the blank icon
3. Click again 
4. Repeat clicking
5. See error

![Screenshot 2022-02-28 220002](https://user-images.githubusercontent.com/100657426/156096653-604252a3-422b-4590-b74d-a6c386a9cc3b.png)
![Screenshot 2022-02-28 220022](https://user-images.githubusercontent.com/100657426/156096655-95f2ed35-15ac-4f42-8eba-b1fe86d33f27.png)
![Screenshot 2022-02-28 220042](https://user-images.githubusercontent.com/100657426/156096656-9b4f2c73-3a1a-4b19-aaf8-2abb6309f5e8.png)

 - OS: [Windows 10, V 21H2]
 - Browser [Chrome]
 - Version [Current as of 9:59 EST 2/28/2022]

**Smartphone (please complete the following information):**

**Comment by DivertedCircle** [comment]
A weapon proficiency being granted has been entered wrong or deleted. This is a problem with the content you have loaded, not a problem with the website.
