### ISSUE TITLE
Feature Request: Add Schedule 6 Spellcaster Progression

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#562]
**Motivation / Use Case**
Adding this will allow custom classes to replicate the Pact Magic feature of the Blood Hunter class (Warlock progression that starts at 3rd level).

**Other Information**
Add spell slot schedule 6 to
https://github.com/Orcpub/orcpub/blob/develop/src/cljc/orcpub/dnd/e5/options.cljc

6 {3 {1 1}
4 {1 2}
5 {2 2}
6 {2 2}
7 {3 2}
8 {3 2}
9 {4 2}
10 {4 2}
11 {5 2}
12 {5 2}
13 {5 3}
14 {5 3}
15 {5 3}
16 {5 3}
17 {5 3}
18 {5 3}
19 {5 4}
20 {5 4}}

**Comment by datdamnzotz** [comment]
Already in the code 
https://github.com/Orcpub/orcpub/blob/develop/src/cljc/orcpub/dnd/e5/options.cljc#L558-L575
Closing.
