### ISSUE TITLE
Is there a mirror to datomic-free available?

### ISSUE THREAD

**Issue by rubydotexe** [Orcpub/orcpub#566]
Hi, I need to build the containers from source because I am using ARM64 architecture. But as everyone knows by now, datomic-free isn't available for download anymore. I was wondering if anyone happened to know where I can download datomic-free version 0.9.5703? 

(Unless theres a way I can easily use the pro-starter version of datomic, that is.)

**Comment by rubydotexe** [comment]
BTW - [CNET](https://download.cnet.com/Datomic-Free/3000-18500_4-75766288.html) provides datomic-free, but only the version up to 0.8.4020.

**Comment by rubydotexe** [comment]
[Softpedia](https://www.softpedia.com/get/Programming/Components-Libraries/Datomic.shtml) has Datomic-Free-0.9.5173. I have no clue if that version is a close enough version though.

**Comment by codeGlaze** [comment]
Hey sorry for the late comment @rubydotexe but that's awesome news! Thank you for digging <3

Datomic's pulling of the free version was... Well, half assed, it seems. Even their website points to the dead link. -_-
