### ISSUE TITLE
Import file suddenly doesn't work anymore

### ISSUE THREAD

**Issue by MrMidget** [Orcpub/orcpub#568]
**Describe the bug**
After making some custom items, feats, backgrounds, races, etc etc. I exported it all as a .orcbrew file.
I then deleted all my content and imported said .orcbrew file. Which was working fine.
Then a couple days later all my custom made stuff is gone, so I try to import that said .orcbrew file again.
But now it says: invalid .orcbrew file.

How did this happen?
I know the file bugs sometimes while exporting, thats why u gotta try before closing all the information, but once it works it should work fine right?

This is on Google Chrome, Windows 10

Anyone with some tips or tricks to help me prevent future loss?

**Comment by DivertedCircle** [comment]
Test your exported file in an incognito window rather than deleting and reimporting it in the same window. Its possible the file was corrupted from the first export but it wasn't caught because it was reuploaded in the same window.
