### ISSUE TITLE
Screen Blacking Out while choosing lvl 3 in Barbarian

### ISSUE THREAD

**Issue by OddGP** [Orcpub/orcpub#577]
**Describe the bug**
Whenever I put barbarian into level 3 my screen blacks out and I am unable to do anything except refresh the page. When I refresh the page it returns me to 

**To Reproduce**

1. Go to 'Class/Level'
2. Click on 'Select Class'
3. Scroll down to 'Barbarian'
4. Click on 'Select Level'
5. Select Level 3
6. See error

**Expected behavior**

A your page will go black and to fix it you have to refresh your page and when you go back into the character sheet you will be able to use every tab except for for Class/Level tab.

**Screenshots**

![image](https://user-images.githubusercontent.com/114527067/192667673-f3ff88c9-d7f6-45bd-acba-7110fb1089db.png)

 - Windows 10
 - Google Chrome

**Comment by DivertedCircle** [comment]
Do you have content loaded in the My Content screen? If yes, there's a good chance your file is corrupted. If no, then its likely a problem with your adblocker. Disable it.

**Comment by codeGlaze** [comment]
Most likely a user issue, not a source issue; eg. Corrupt files or ad blockers.

Closing
