### ISSUE TITLE
Magic item does not increase AC

### ISSUE THREAD

**Issue by anttitelio** [Orcpub/orcpub#580]
**Describe the bug**
I am wearing a Ring of Protection (AC+1), but it does not increase my AC

**To Reproduce**

1. Check the Armor Class of the character
2. Go to 'Equipment -> Other Magic Items'
3. Click on 'Ring of Protection'
4. See if the AC changed from step 1

**Expected behavior**

AC should have increased by 1

**Desktop (please complete the following information):**

 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 106.0.1 (64-bit)

**Comment by codeGlaze** [comment]
I can't replicate this.
It works on a test character on a fresh reload of the page. 

Occasionally you need to unequip/reequip items to retrigger the JS calculations.
I'm going to close this for now, thank you.
