### ISSUE TITLE
Add rounded corners to character images

### ISSUE THREAD

**Issue by 2br-2b** [Orcpub/orcpub#586]
Thank you guys so much for making this site! It's making it so much easier for me to learn how to play D&D with my friends!

**Motivation / Use Case**

It's a very small change, but this would be a nice, very quick addition:

![image](https://user-images.githubusercontent.com/43968991/216739826-1d09564e-905d-4b39-9f9e-bfaec5d45a90.png)

![image](https://user-images.githubusercontent.com/43968991/216739816-7a30c008-aca0-4434-b001-ebdee9f25ea4.png)

Just adding the `border-radius:5px` style to all the character images would make them look slightly nicer and feel slightly more polished.

**Expected Behavior**

Character profile pictures having a small corner radius to make the corners slightly less jarring.

**Other Information**

This can be added via custom css, but it'd be nice if it were built into the site. I'd try to add this myself, but I haven't worked in Clojure before, plus this (seems like) a small change.

**Comment by 2br-2b** [comment]
I think the change would be here: https://github.com/Orcpub/orcpub/blob/9557dcfc252ce25114d69316a2c3e80101c5d5c5/src/cljs/orcpub/character_builder.cljs#L1742-L1744

Changing that to:

```Clojure
 (def image-style 
   {:max-height "100px" 
    :max-width "200px"
    :border-radius "5px"}) 
```

I may open a PR later

**Comment by codeGlaze** [comment]
Added with either/both #587 and #593

Closing :D
