### ISSUE TITLE
Emails for account verification and reset password never arrived

### ISSUE THREAD

**Issue by SirKen-IT** [Orcpub/orcpub#591]
After registering the verification email never arrived. Same thing for the password reset email.
I tried with two different email addresses, gmail and outlook, they are not even in spam.

Isn't there a procedure to resend the verification email or a way to bypass the problem?

**Comment by datdamnzotz** [comment]
https://www.dungeonmastersvault.com/help/im-not-getting-my-signup-password-reset-email/
