### ISSUE TITLE
Inputs not retaining info

### ISSUE THREAD

**Issue by Sotdyeti** [Orcpub/orcpub#597]
**Describe the bug**
Info put in the Experience Points, Image URL (128k max image size for PDF) are not being retained after save.

Windows 10
Google Chrome
Version 114.0.5735.134 (Official Build) (64-bit)

**Comment by datdamnzotz** [comment]
Saves appear to work just fine for XP and Images.
Double check your image source we do remove invalid images.
https://www.dungeonmastersvault.com/help/images-keep-disappearing/
