### ISSUE TITLE
It saved the file as a TXT not a orcbrew. So I lost all my progress

### ISSUE THREAD

**Issue by MRDOGHOG** [Orcpub/orcpub#598]
I was basically doing normal Dungeon Master Valut things. I made this really cool class and I was really proud! So I downloaded it. But instead of it being a .orcbrew it was a .txt. I didn't think much of it until my progress was lost. So i opened it to see that it was a txt no a orcbrew. Why was it a txt, can you explain how i can save my files please?

**Comment by datdamnzotz** [comment]
It's probably the browser you used to download it with.  
Rename it to <whatever>.orcbrew and try reuploading.

**Comment by DivertedCircle** [comment]
> It's probably the browser you used to download it with. Rename it to .orcbrew and try reuploading.

I've noticed this happens when downloading in Chrome but you run an extension for managing downloads.

**Comment by DivertedCircle** [comment]
> 

If you get this fixed, keep in mind an orcbrew file is not meant to be a readable format. Even exported properly it will look like a jumble of code.

**Comment by codeGlaze** [comment]
This is a semantic difference and not an issue with the site/project itself. As long as data was saved to the file it should work by renaming the extension to `.orcbrew`.

Closing
