### ISSUE TITLE
Missing Account

### ISSUE THREAD

**Issue by YeetiumTypeZ** [Orcpub/orcpub#599]
My account is missing

i had an account with multiple custom races and classes in it but now it is saying that my email is not linked to any account. Note i do have the original verification email.

I didn't use the website for about a year and now that i'm back it is just gone along with all my progress.

**Comment by Jessomadic** [comment]
@YeetiumTypeZ Sorry to hear that!
Every year we purge Accounts that haven't been used in a year to save on storage costs. We always send out email reminders.

**Comment by YeetiumTypeZ** [comment]
is there any way to recover it

**Comment by Jessomadic** [comment]
Only person that might have a shot at it is @codeGlaze but I dont want to promise anything

**Comment by datdamnzotz** [comment]
@YeetiumTypeZ 
We hope this message finds you well. We wanted to clarify the purpose of GitHub issues. GitHub issues are primarily used for coding issues and development discussions related to our platform. If you are facing any technical difficulties or have questions regarding your account on Dungeon Masters Vault, we kindly request you to reach out to our dedicated support team at support@dungeonmastersvault.com.

Our support team will be more than happy to assist you with any account-related queries or concerns you may have. They are well-equipped to provide the necessary guidance and ensure you have a seamless experience on our platform.

Thank you for your understanding and cooperation.
