### ISSUE TITLE
Mobile version of "view character" page missing spells

### ISSUE THREAD

**Issue by Dreherjd** [Orcpub/orcpub#600]
**Describe the bug**
The desktop version of the view character page shows my spells, however, the mobile version only shows maybe half of the spells my character knows.
It also affects generating a character sheet, as it pulls the spells from what's in the spell list. So generating a sheet from the desktop version works just fine, whereas generating a sheet from a mobile device gives an incomplete spell list.

**To Reproduce**

1) view a character with spells on the desktop version, and note the spells they have access to.
2) open the mobile version of the same character, note that it only shows half the spells the character has access to.

**Expected behavior**

The mobile version of the site should list the same spells as the desktop version.

**Screenshots**

Desktop screenshot:
![desktopCharSheet](https://github.com/Orcpub/orcpub/assets/31300182/5ca2ab54-950d-40e9-9f5d-55142fc1ec89)
Mobile Screenshot:
![Screenshot (Oct 25, 2023 11_19_11 AM)](https://github.com/Orcpub/orcpub/assets/31300182/865892ba-3ba3-41b5-b6b6-49e7e5dd8113)

**Desktop (please complete the following information):**

 - OS - Windows 10
 - Browser  - Chrome
 - Version - Version 118.0.5993.118 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

 - Device: LG V60 ThinQ 5g
 - OS: Android 13
 - Browser Chrome
 - Version 118.0.5993.111

**Additional context**

**Comment by datdamnzotz** [comment]
WitchBolt and Lighting lure aren't srd.
Make sure you load the same orcpub file you used in your browser to create that character. You need to load it on your phone as well.

**Comment by Dreherjd** [comment]
That did it, thanks!
