### ISSUE TITLE
How do I mount homebrew.orcpub in docker-compose?

### ISSUE THREAD

**Issue by rubydotexe** [Orcpub/orcpub#603]
I don't understand [these instructions](https://github.com/Orcpub/orcpub/tree/develop/deploy/homebrew). I realize this is potentially a dumb question but I can't find a direct answer to this. The instructions just say to add the orcbrew file in the deploy folder, but the deploy folder isn't mounted anywhere in the docker container for Orcpub or Datomic? Where should I mount it so that its automatically loaded?

**Comment by datdamnzotz** [comment]
It is mounted here:
https://github.com/Orcpub/orcpub/blob/develop/docker-compose.yaml#L44

and used by nginx right here to publish it:
https://github.com/Orcpub/orcpub/blob/develop/deploy/nginx.conf#L31-L33

download the raw version of [docker-compose.yaml ](https://raw.githubusercontent.com/Orcpub/orcpub/develop/docker-compose.yaml) and drop it in any directory.  e.g. /home/orcpub/docker-compose.yaml

Create the deploy directory. eg. /home/orcpub/deploy/
Download all the files and directories from https://github.com/Orcpub/orcpub/tree/develop/deploy/ into /home/orcpub/deploy/

chmod +x snakeoil.sh
Run ./snakeoil.sh

So now you should have:
/home/orcpub/deploy/
/home/orcpub/deploy/docker-compose.yaml
/home/orcpub/deploy/snakeoil.key
/home/orcpub/deploy/snakeoil.crt

Create your homebrew.orcbrew in 
/home/orcpub/deploy/homebrew/homebrew.orcbrew

docker-compose up -d to run it in the background.

You will end up with:
/home/orcpub/deploy/
/home/orcpub/data/   <-this is where your database lives.
/home/orcpub/logs/

**Comment by rubydotexe** [comment]
Is nginx the only way to deploy these? I am using a different reverse proxy named [pomerium](https://www.pomerium.com/docs/reference) - so I assume I would need to find the equivalent configuration for this reverse proxy?

**Comment by datdamnzotz** [comment]
Nope, you can use whatever reverse proxy you want, that's just the one in the docker image/compose file for ease of use.  

You can replace 
https://github.com/Orcpub/orcpub/blob/develop/docker-compose.yaml#L35-L46
with any reverse proxy you are comfortable with.

On the main website we run we are using traefik as the reverse proxy and publish to a couple backend apps.  We don't use nginx at all.
