### ISSUE TITLE
Facebook login not working

### ISSUE THREAD

**Issue by istumpf** [Orcpub/orcpub#61]
**Description of the bug**
Facebook app seems to be in developers mode

**To Reproduce**
1. Click on login with facebook button

**Screenshots**
![image](https://user-images.githubusercontent.com/8162419/51621538-e353aa80-1f1b-11e9-8e46-f55709449e5a.png)

**Desktop:**
 - OS:  macOs Mohave and Windows 10
 - Browser: Chrome last version

**Comment by DivertedCircle** [comment]
This is a known issue. You'll have to use the other method to login.

**Comment by datdamnzotz** [comment]
Won't fix see #316
