### ISSUE TITLE
[Bug] Duplicate Spells Displays

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#68]
**Describe the bug**
The spells Booming Blade, Green-Flame Blade, and Sword Burst display twice in the spell selection page when the homebrew Sword Coast Adventure's Guide content is loaded. This seems to be due to the spells being improperly removed from the website when non-SRD content was removed. The spell Lightning Lure from the same source content displays properly.

**To Reproduce**
1. Upload the SCAG file to My Content.
2. Create a spellcasting class that uses the sorcerer, warlock, or wizard spell lists. Can also be done with the Magic Initiate feat.
3. Go to the Spells tab to choose your spells.
4. See error.

![image](https://user-images.githubusercontent.com/26470570/51999821-dcc3b680-2478-11e9-9f3e-84a411e30ee9.png)

**Comment by DivertedCircle** [comment]
After testing more I've discovered this only occurs when selecting spells for the Magic Initiate feat and then only when Wizard is the class selected for the feat.

**Comment by Demonsthere** [comment]
Those spells are in two books: SCAG and XGE, that can be the reason you see it twice

**Comment by DivertedCircle** [comment]
Those spells are SCAG only, they do not appear in XGE.
