### ISSUE TITLE
Add Subclass Name to PDF

### ISSUE THREAD

**Issue by DivertedCircle** [Orcpub/orcpub#80]
**Is your feature request related to a problem? Please describe.**
PDF's only display the name of your base class, not your subclass.

**Describe the solution you'd like**
Add a section to the PDF that displays subclass.

**Comment by Demonsthere** [comment]
This is a quite easy fix, but it can be messy with multiclassing:

![zrzut ekranu 2019-02-18 o 16 28 58](https://user-images.githubusercontent.com/13346689/52961041-5a088a00-339a-11e9-90dd-97bfea49e302.png)
![zrzut ekranu 2019-02-18 o 16 29 12](https://user-images.githubusercontent.com/13346689/52961042-5a088a00-339a-11e9-8a23-05d345b63d39.png)

We might want to move the subclass info to a different place, or leave it like this, dunno :)

**Comment by datdamnzotz** [comment]
We may consider redoing the form for a bigger input text box.

**Comment by Demonsthere** [comment]
We have to redo the form, as it only allows a single line of text, we cannot input a multiline string there
