### ISSUE TITLE
Document for setup

### ISSUE THREAD

**Issue by Demonsthere** [Orcpub/orcpub#9]
As we have moved to a `docker-compose` setup, and the DB initialisation has been resolved within connection, we need to update the `README.md` to reflect the changes. 
Bonus: create a `docs` dir and split the documentation into topics

**Comment by codeGlaze** [comment]
GH has a wiki.
I just created the Home page, nothing on it... Yet. >.>

**Comment by Demonsthere** [comment]
We now have an updated README in the repo + setup instructions for linux and windows in the wikis.
